### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ilanbiala** [floridoo/gulp-sourcemaps#100]
It would be nice to have a changelog to know what has changed in terms of API, performance, bugs, etc.

**Comment by ai** [comment]
@floridoo @shinnn Without Changelog I didn’t know what is new in 1.5.0 and is it safe to update version.

**Comment by floridoo** [comment]
Done (for 1.4.0 and 1.5.0). See https://github.com/floridoo/gulp-sourcemaps/releases.

**Comment by Schweinepriester** [comment]
Changelog seems to be missing again since 1.7.1 & 2.0.0?

**Comment by axelson** [comment]
Yes, there appears to be no changelog listed for the upgrade to 2.0. Which makes it unclear what needs to be done to upgrade to 2.X. I'd really prefer to not need to "remove node_modules then run npm install and pray that nothing broke". It appears that the only breaking changes are related to dependency updates? Is that correct?

https://github.com/gulp-sourcemaps/gulp-sourcemaps/issues/225

**Comment by WuglyakBolgoink** [comment]
@floridoo  any news hire?
![image](https://user-images.githubusercontent.com/2271337/53229101-94687480-3683-11e9-8da2-e3ea5b8c8a2d.png)

**Comment by phated** [comment]
@WuglyakBolgoink he doesn't work on the project anymore.
