### ISSUE TITLE
Import inline css no longer works with sourcemaps

### ISSUE THREAD

**Issue by Tivoli** [floridoo/gulp-sourcemaps#101]
Getting the following error when using ```@import (inline) './myfile.css';```

```
Potentially unhandled rejection [2] Error: ENOENT: no such file or directory, open '__stdin__.css'
    at Error (native)
```

If I remove gulp-sourcemaps then the less files compile without error.

**Comment by heikki** [comment]
Do you have other plugins there?

**Comment by Tivoli** [comment]
Yep, less-plugin-clean-css, less-plugin-autoprefix,and less-plugin-npm-import. It was all working previously, until I updated to the latest gulp-sourcemaps.

**Comment by heikki** [comment]
Try disabling plugins to pinpoint the problem. 

less-plugin-autoprefix is one suspect: https://github.com/less/less-plugin-autoprefix/issues/7

**Comment by Tivoli** [comment]
less-plugin-clean-css also causes an issue, had to remove both.

**Comment by maxisam** [comment]
Change the sequence of clean and autoprefix will work. clean first.
