### ISSUE TITLE
improvement: extendable sourceMapName

### ISSUE THREAD

**Issue by igorlino** [floridoo/gulp-sourcemaps#102]
The [Source Map Revision 3 Proposal](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/)

tells that the naming convention is optional.

The gulp-sourcemaps library is deriving the name for the  .map that is generated. What about making a bit it more extensible to enable the "optional" part of the naming convention?
I mean, one of the benefits of gulp itself is the ability to code and enable coding over fixed configurations ("code over configuration"). This feature goes with that design principle. 

(If help is needed, I could create a PR if you like).

It should not have any side-effect to existent functionality since the important is that the actual map file exists and is mapped.

An example of the code would then look like this:

   gulp.task('javascript', function() {
   gulp.src('src/*/.js')
   .pipe(sourcemaps.init({sourceMapName: function(path) {
   //whatever logic here. path includes the filename
   return path + '.map'; 
   }}))
   .pipe(plugin1())
   .pipe(plugin2())
   .pipe(sourcemaps.write())
   .pipe(gulp.dest('dist'));
   });

**Comment by igorlino** [comment]
The idea for the improvement came from: https://github.com/floridoo/gulp-sourcemaps/issues/91
It's in principle/ fact not related, as that issue is a bug from another library.

**Comment by dellheng** [comment]
+1 this very useful feature

this my code

```
    .pipe(sourcemaps.write('../../build', {includeContent: false, sourceRoot: '/',
      sourceMappingURLPrefix: 'http://localhost:8000'}))
    .pipe(gulp.dest(paths.dist + '/js'));
```
this result
//# sourceMappingURL=http://localhost:8000/../build/app.min-42edcc2b10.js.map

but I want code is 
```
    .pipe(sourcemaps.write('../../build', {includeContent: false, sourceRoot: '/',
      sourceMappingURL: function(mapFileName) {
        return 'http://localhost:8000/' + mapFileName
      }
    }))
    .pipe(gulp.dest(paths.dist + '/js'));
```
result is 
//# sourceMappingURL=http://localhost:8000/app.min-42edcc2b10.js.map

**Comment by floridoo** [comment]
This is now possible through the `sourceMappingURL` option

**Comment by igorlino** [comment]
Thanks a lot!
+1
