### ISSUE TITLE
State in README that only one files type is supported at a time

### ISSUE THREAD

**Issue by vmarkovtsev** [floridoo/gulp-sourcemaps#103]
As I experienced, gulp-sourcemaps supports only one file type per pipeline. That is, the following code
```js
gulp.src(['*.js, *.css'])
.pipe(sourcemaps.init())
.pipe(gulpif('*.js', uglify()))
.pipe(gulpif('*.css', minifyCss()))
.pipe(sourcemaps.write())
.pipe(gulp.dest('dist'))
```
generates only Javascript or CSS maps (depending on whatever file type comes first) *but not both*. This prevents from using gulp-sourcemaps with such plugins as gulp-useref, as they use a single pipeline for all assets.
You should write about this limitation somewhere on the visible place.

**Comment by floridoo** [comment]
This should work from `gulp-sourcemaps`' side. Every file is handled independently, so it's almost impossible this is `gulp-sourcemaps`' fault. Could be an issue with `gulp-if`.
