### ISSUE TITLE
.write() with no parameter is not writing maps

### ISSUE THREAD

**Issue by SamVerschueren** [floridoo/gulp-sourcemaps#105]
Hi

I am converting my Grunt build task to Gulp and am now uglifying my code and adding sourcemaps to it. This is my build task (for now).

```JavaScript
gulp.task('build', function() {
    gulp.src(['app/controllers/Controller.js', 'app/controllers/TitleBarController.js', 'app/controllers/**/*.js'])
        .pipe(sourcemaps.init())
        .pipe(concat('Controllers.js'))
        .pipe(uglify())
        .pipe(rename('Controllers.min.js'))
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('dist'));
});
```

The only thing this does is writing my ```Controllers.min.js``` file to the ```dist`` folder, no map file is added. 

When I change the ```sourcemaps.write()``` line call to ```sourcemaps.write('.')``` it works. Is the parameter really necessary? Am I missing something here?

Thanks.

**Comment by floridoo** [comment]
See README:
* no parameter: write inline source maps (included in your .min.js file)
* with parameter: write the source map to a file
