### ISSUE TITLE
sources not shown with includeContent=true and sourceRoot set.

### ISSUE THREAD

**Issue by Nirazul** [floridoo/gulp-sourcemaps#106]
**Type:** Bug

**Version:** above v1.3.0, latest Chrome

**Description**:
When updating gulp-sourcemaps from 1.3.0 to a higher version, sourcemaps will be loaded, but original files are not shown in devtools even though includeContent is set to true.

gulp-task:
```
var env = util.env();
var hasError = false;

gulp.src(config.sass.src.files)
    .pipe( $.plumber({ errorHandler: util.error }) )
    .pipe( $.sourcemaps.init({}) )
    .pipe( $.sass({ onError: errorFn }) )
    .pipe( $.autoprefixer(config.sass.plugins.autoprefixer) )
    .pipe( $.sourcemaps.write('.', config.sass.plugins.sourcemaps) )
    .pipe( gulp.dest(config.sass.build.path) );
```

`config.sass.plugins.sourcemaps` equals: 
```
{
    includeContent: true,
    sourceRoot: 'source-scss:///'
}
```

Interestingly, when sourceRoot is left empty ( -> equals "/source/") everything works fine.

The reason why I'd like to set this sourceRoot is to copy webpack behaviour whose sourcemaps are shown in the browser as 'webpack://'. 
I could achieve a similar effect (tested to be working) by manually editing the sourcemap with following steps:
- Every path in the `sources`-Array is prefixed with `source-scss:///`
- `sourceRoot` is an empty string

I was unable to get this effect with the options provided by gulp-sourcemaps, however.

How can I achieve this?

**Comment by MikaAK** [comment]
If include content is set to true, then it will read from `/source/` otherwise you must set it to `includeContent` to false and set the `sourceRoot` I believe. 

Try setting `sourceMappingURLPrefix` to `source-scss:///` and `includeContent` to `false`

**Comment by Nirazul** [comment]
When I set `sourceMappingURLPrefix` to `source-scss:///` Chrome looks for the map file at `source-scss:///styles.css.map`, which obviously doesn't exist.

My suggestion is to add a case when `includeContent` is set to true (so there's no need for the sourceRoot property anywhere, right?):
If `includeContent` is set to `true` and `sourceRoot` is an URL, leave `sourceRoot` empty and add the `sourceRoot` property to every path in the sources-array.

```
// gulp-sourcemaps options
{
    includeContent: true,
    sourceRoot: 'source-scss:///'
}
```

Instead of:
```
// styles.css.map
{
    "version": 3,
    "sources": [
        "vendor/reset.scss",
        <etc>
    ],
    <etc>
    "sourceRoot": "source-scss:///"
}
```

I should get:
```
// styles.css.map
{
    "version": 3,
    "sources": [
        "source-scss://vendor/reset.scss",
        <etc>
    ],
    <etc>
    "sourceRoot": ""
}
```
 
Another possibility would be to work with sourceMappingURLPrefix:
```
// gulp-sourcemaps options
{
    includeContent: true,
    sourceRoot: "",
    sourceMappingURLPrefix: 'source-scss:///'
}
```

What do you think about it? Because it was working with 1.3.0, it feels like a regression to disallow this behaviour now.

**Comment by aguynamedruchir** [comment]
+1

**Comment by Nirazul** [comment]
Maybe this helps anyone. I've finally figured out, how to fix the empty sourcemap files by using `sourceRoot` as a function.

I have the following setup:

**files:**
```
main-file 1: <src-dir>/src/scss/app/main.scss
main-file 2:  <src-dir>/src/scss/utils/utils.scss
```

**pipe stream**
```
return gulp.src('**/*.scss',
    { cwd: '<src-dir>/scss' }
)
    .pipe( sourcemaps.init() )
    .pipe( sass() )
    .pipe( sourcemaps.write('.', {
        includeContent: true,
        sourceRoot: function(file) {
            var dir = path.dirname(file.relative);
            return path.join('<src-dir>', 'scss', dir);
        }
    }) )
    .pipe( filterMap.restore({ end: true }) )
    .pipe( gulp.dest('<dist-dir>/scss/dist') );
```

The underlying problem is that `gulp-sourcemaps` usese `file.base` when no `sourceRoot` is provided. `file.base` is not necessarily the directory the source files are in. So I needed to correct the sourceRoot according to the current main file.

With this setup I received correct sourcemaps once again. Be aware that `gulp-autoprefixer` killed them again. I was forced to switch to `postcss` with `autoprefixer` as a plugin.
