### ISSUE TITLE
Warning 'util.error: Use console.error instead' polluting the output

### ISSUE THREAD

**Issue by simonrenoult** [floridoo/gulp-sourcemaps#109]
Hi,

I was building a gulp task including browserify like this : 

```js
gulp.task('scripts', function() {
  browserify('./src/main.js', {debug: true})
      .transform(hbsfy)
      .transform(babelify)
      .bundle()
      .on('error', utils.swallowError)
  	  .pipe(source(conf.paths.js.app))
  	  .pipe(buffer())
  	  .pipe(uglify())
  	  .pipe(gulp.dest(conf.paths.dist));
});
```

I then added sourcemaps like this : 

```js
gulp.task('scripts', function() {
  browserify('./src/main.js', {debug: true})
      .transform(hbsfy)
      .transform(babelify)
      .bundle()
      .on('error', utils.swallowError)
  	  .pipe(source(conf.paths.js.app))
  	  .pipe(buffer())
      .pipe(sourcemaps.init({loadMaps: true}))
  	  .pipe(uglify())
      .pipe(sourcemaps.write('./'))
  	  .pipe(gulp.dest(conf.paths.dist));
});
```

Which works fine (the sourcemaps is correctly generated) but the prompt output is polluted a lot, as shown below :

````
[22:31:33] Using gulpfile ~/Projects/website/gulpfile.js
[22:31:33] Starting 'scripts'...
[22:31:33] Finished 'scripts' after 31 ms
util.error: Use console.error instead
WARN: Couldn't figure out mapping for ?:2,0 → 1,454 []
util.error: Use console.error instead
WARN: Couldn't figure out mapping for ?:4,0 → 1,466 []
util.error: Use console.error instead
[...] # Hundreds of lines like the ones above
WARN: Couldn't figure out mapping for ?:171,25 → 1,4579 []
util.error: Use console.error instead
WARN: Couldn't figure out mapping for ?:173,11 → 1,4600 []

Process finished with exit code 0
````

As you can guess, this makes the prompt really difficult to read. 

I've looked around and it seems to happen on the yuidoc plugin too (see [here](https://github.com/yui/yuidoc/issues/325)) since one of their dependency (yui) is using util.error which has been deprecated in Node 0.12. I've tried to find the incriminated dependency but it goes quite deep.  Any work around suggestion ? Like filtering the output or something ?

Any idea is very welcomed :)

**Comment by floridoo** [comment]
None of the packages `gulp-sourcemaps` depends on is using `util.error`.
* Are your dependencies up to date? (run `npm update`)
* Is the error still there if you comment out the plugins between `sourcemaps.init` and `sourcemaps.write`?
