### ISSUE TITLE
Extra relative path in map comment

### ISSUE THREAD

**Issue by pikeas** [floridoo/gulp-sourcemaps#111]
Gulp task:

```javascript
sourcemaps = require('gulp-sourcemaps');
stylus = require('gulp-stylus')

gulp.task('test', function() {
    return gulp.src('src/**/*.styl')
    .pipe(sourcemaps.init())
        .pipe(stylus({sourcemap: {inline: false}}))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('dist'));
});
```

This creates CSS files with the following comment: `/*# sourceMappingURL=../styles/screen.css.map */` The first part of the path, `../styles`, is redundant, because the sourcemap is written to the same directory as the file (`sourcemaps.write('.')`). The comment should be `/*# sourceMappingURL=screen.css.map */`.

The same thing happens with the gulp-coffee plugin, so this looks like an issue with gulp-sourcemaps, which is common to both.

**Comment by rasmusbe** [comment]
Same problem for me with:
```javascript
var path = "web/app/themes/white";
return gulp.src([path + '/js/vendor/*.js', path + '/js/white.js'])
    .pipe(sourcemaps.init())
      .pipe(concat(path + '/js/white.min.js'))
      .pipe(uglify())
    .pipe(sourcemaps.write('.', {
      includeContent: false
    }))
    .pipe(gulp.dest('.'));
```

**Comment by dak** [comment]
I'll just add to this that setting `sourceMappingURLPrefix` to `./` also failed to fix this problem.

**Comment by siready** [comment]
I'm experiencing exactly the same problem here.

**Comment by floridoo** [comment]
In case newer versions don't fix this, try the new `sourceMappingURL` option, which allows full control over the URL.
