### ISSUE TITLE
Question: External sourcemap not generated but source mapping url comment is added

### ISSUE THREAD

**Issue by raghur** [floridoo/gulp-sourcemaps#115]
@floridoo 

I'm trying to uglify and generate sourcemaps conditionally. When I do it in my task stream individually, it works. However, if I pull out the three actions (`sourcemaps.load`, `uglify`, `sourcemaps.write`), then it only works if I don't specify a relative path (ie inline sourcemap in the js). 

My gulp file is here: [gulpfile.js](https://gist.github.com/raghur/734447b813e66113d7f9#file-gulpfile-js).
In the current form it works as expected. If I comment out L86-88 and uncomment L89, then only the inline sourcemap works.

PS: I also posted to SO [here](http://stackoverflow.com/questions/29788502/gulp-sourcemaps-strange-behavior)?

**Comment by 1player** [comment]
A bit late but may be useful to somebody: had the same problem, apparently my source map files were created in another directory than what I expected.
