### ISSUE TITLE
Disable programmatically?

### ISSUE THREAD

**Issue by milesj** [floridoo/gulp-sourcemaps#119]
Is there any easy way to do this? Say I pass `gulp --no-sourcemaps` to the CLI, I want to disable sourcemaps from the Gulp layer.

```js
gulp.task('css', function() {
    return gulp.src(config.css.src + '/**/*.scss')
        .pipe(sourcemaps.init())
            .pipe(sass())
            .pipe(prefixer({
                browsers: ['last 3 versions'],
                cascade: false
            }))
        .pipe(sourcemaps.write('../maps/css', { enabled: options.sourcemaps })) // HERE or something similar
        .pipe(gulp.dest(config.css.dst));
});
```

**Comment by floridoo** [comment]
You can use the normal javascript `if` statement to remove `sourcemaps.init()` and `sourcemaps.write()` from the pipeline. Another option is the `gulp-if` plugin.

**Comment by milesj** [comment]
`gulp-if` looks like the better option. Thanks!
