### ISSUE TITLE
Speeding up gulp-sourcemaps (caching?)

### ISSUE THREAD

**Issue by andreialecu** [floridoo/gulp-sourcemaps#121]
I have a relatively large project and gulp-sourcemaps seems to take a significant amount of the build time.

I'm using gulp-cached and gulp-remember for the bulk of my build, but I couldn't see any way to implement caching into the sourcemaps building step. 

Rebuilds now take ~4-5 seconds with gulp-cached (from 25+ sec). And if I disable sourcemap output, they take under one second - so it seems like sourcemaps accounts for 70% of the time spent now.  I'm running on an SSD so I/O performance shouldn't be an issue. 

Any ideas how I can shave off some of those extra seconds?

**Comment by floridoo** [comment]
This plugin probably isn't the one taking more time, it's the actual source map generation in the different plugins that's expensive. It should be possible to cache their source map output (like you can cache the normal output), but this plugin is probably not the right place to do it.
