### ISSUE TITLE
Sourcemap doesn't map properly after multiple transformations 

### ISSUE THREAD

**Issue by marvinhagemeister** [floridoo/gulp-sourcemaps#124]
I just recently began using gulp in my workflow, but I have some troubles setting up sourcemaps for multiple transformations. The sourcemaps are generated successfully, but they never map back to the original scss files. Instead they map back to the compiled sass file (in this case `app.css`).

I tried various different supported plugins besides postcss, but they all exhibit the same behaviour. When I don't use any plugin after `sass` (except `gulp-rename`) everything works fine, though.

Has anyone encountered this issue as well?

```javascript
var gulp       = require('gulp');
var sass       = require('gulp-sass');
var rename     = require('gulp-rename');
var sourcemaps = require('gulp-sourcemaps');
var postcss    = require('gulp-postcss');

gulp.task('styles' function() {
  return gulp.src('sass/app.scss')
    .pipe(sourcemaps.init())
      .pipe(sass())
      .pipe(postcss([
        require('cssgrace'),
        require('autoprefixer'),
        require('pixrem'),
        require('cssnano')
      ])
      .pipe(rename({
         basename: 'style',
         suffix: '.min',
         extname: '.css'
      }))
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest('dist/css/'));
});
```
Generates:
```javascript
./dist/css/style.min.css
./dist/css/style.min.css.map // Doesn't map back to *.scss files
```

**Comment by gussyboy** [comment]
I've got the same issue, but I believe it's all related to this - https://github.com/sindresorhus/gulp-autoprefixer/issues/8

**Comment by tarruda** [comment]
Same issue here, here's my transform pipeline:

```js
  return gulp.src('src/**/*.ts', {base: '.'})
    .pipe(sourcemaps.init())
      .pipe(ts({typescript: typescript, noImplicitAny: true, target: 'ES6'})).js
      .pipe(babel())
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('build'));
```

The resulting source maps only contain information about the es6 files generated by the first pass of the transformation(typescript -> es6)

**Comment by Jiasm** [comment]
Autoprefixer will change ```*.css``` files, but sourcemap can't know, so execute autoprefixer before sourcemap.
