### ISSUE TITLE
all.js gets longer every time my gulp concat task is executed

### ISSUE THREAD

**Issue by Jones-S** [floridoo/gulp-sourcemaps#125]
I'm not exactly sure what's happening here, but did someone experience a similar thing?

I have a gulpfile:

```javascript
// Load Node Modules/Plugins
var gulp = require('gulp');
var concat = require('gulp-concat');
var notify = require('gulp-notify');
var minifyCSS = require('gulp-minify-css');
var sourcemaps = require('gulp-sourcemaps');
var sass = require('gulp-sass');


// Asset paths
var paths = {
  sass: ['exercise-03/scss/*.scss'],
  css:  ['exercise-03/css/'],
};


gulp.task('sass', function() {
    gulp.src('exercise-03/scss/main.scss')
        .pipe(sourcemaps.init())
        .pipe(sass())
        .pipe(sourcemaps.write('maps'))
        .pipe(gulp.dest('exercise-03/css'))
        .pipe(notify({ message: 'Sass complete' }));
});



// concat gulp task
gulp.task('concatenate', function() {
    return gulp.src('exercise-03/js/*.js')
        .pipe(sourcemaps.init())
        .pipe(concat('all.js'))
        .pipe(sourcemaps.write('maps'))
        .pipe(gulp.dest('exercise-03/js'))
        .pipe(notify({ message: 'Concatenate task complete' }));
});


// Watch Task
gulp.task('watch', function() {
    // watch scss files
    gulp.watch(paths.sass, ['sass']);

    // Watch .js files
    gulp.watch('exercise-03/js/*.js', ['concatenate']);
});


// Default Task
gulp.task('default', ['watch']);
```

After running my gulp watch task and making changes to one of my js-Files
my all.js saves the new part but leaves the old part inside. that results in a file, which gets longer every time my concat task is executed.
But I don't understand, what's the problem...

To illustrate the problem I have only one .js file where I only print out a comment in the console:

```javascript
        console.log("first change made 01");
```

I changed the comment three times increasing the number every time:
the resulting all.js always added the new js-code at the end:

```javascript
        console.log("first change made 01");



//# sourceMappingURL=maps/all.js.map
        console.log("first change made 01");



//# sourceMappingURL=maps/all.js.map
        console.log("first change made 01");



//# sourceMappingURL=maps/all.js.map
        console.log("first change made 02");



//# sourceMappingURL=maps/all.js.map
        console.log("first change made 02");



//# sourceMappingURL=maps/all.js.map
        console.log("first change made 03");



//# sourceMappingURL=maps/all.js.map
        console.log("first change made 03");



//# sourceMappingURL=maps/all.js.map
```
If someone could help me out here, that would be great!

**Comment by marvinhagemeister** [comment]
Hmm I can't reproduce the problem on my machine with your gulpfile. Did you check that all your dependencies are current?

**Comment by Jones-S** [comment]
I installed all gulp-plugins within the last two days. Or are there any other dependencies I would have to think about?
Could there be a problem with the folders for the sourcemaps?
If not I will try to update all dependencies and try it again...
Thanks for answering that quickly though! 
Really appreciate it.

**Comment by marvinhagemeister** [comment]
Nah, that was just a wild guess with the dependencies. I think I found a way to reproduce your problem. This bug always occurs when the source and the destination path are exactly the same:

Simple testcase:
```javascript
var gulp       = require('gulp');
var concat     = require('gulp-concat');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('concatenate', function() {
  return gulp.src('js/**/*.js') // <-- same path as `gulp.dest`
    .pipe(sourcemaps.init())
      .pipe(concat())
    .pipe(sourcemaps.write('maps'))
    .pipe(gulp.dest('js')); // <-- same path as `gulp.src`
});
```
Workaround change the destination path to something other than the source one, e.g.:
```javascript
return gulp.src('js/**/*.js')
    ...
    .pipe(gulp.dest('dist/js/')); // must be different
```

**Comment by Jones-S** [comment]
Ah alright. I did not try this. Thanks for that I will try it asap.
Thank you very much! :v:

**Comment by marvinhagemeister** [comment]
That's great to hear! After giving it some more thought I came to the conclusion that this is not a bug at all but expected behavior. Since both the source file and the output file were in the same directory, they both were matched by the glob pattern in `gulp.src`.

The folder structure at the beginning:
```sh
./js/myscript.js
```
After the first run:
```sh
./js/myscript.js
./js/all.js
```
Now the glob pattern `js/**/*.js`  in `gulp.src` matches both `./js/myscript.js` and `./js/all.js`. Both files are concatenated again and `gulp.dest` then overwrites the existing `./js/all.js` with the new stream content.

After second run:
```sh
./js/myscript.js
./js/all.js # contains myscript.js and the previous version of all.js
```
I think this not a problem with gulp-sourcemaps but with the glob pattern (or folder structure for that matter). Feel free to close this issue.

**Comment by Jones-S** [comment]
Ah that makes sense. That also explains why I had my terminal telling me that my concat task was finished twice...
Thanks for the further explanations!
