### ISSUE TITLE
Getting Potentially unhandled rejection [2] Error: ENOENT

### ISSUE THREAD

**Issue by neonwired** [floridoo/gulp-sourcemaps#127]
So the below works fine.

```
gulp.src('/css/*.less')
        .pipe(sourcemaps.init())
            .pipe(concat('styles.less'))
            .pipe(less())
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('/css/'));
```

However as soon as i add any other plugin e.g. gulp-using I get 'Potentially unhandled rejection [2] Error: ENOENT, open 'C:..................styles.less'
    at Error (native);

```
gulp.src('/css/*.less')
        .pipe(using())
        .pipe(sourcemaps.init())
            .pipe(concat('styles.less'))
            .pipe(less())
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('/css/'));
```

**Comment by geirsagberg** [comment]
Same error here, works fine if I do not use any plugins, or if I do not write sourcemaps. Once I do both, I get the same error.

**Comment by andreykl** [comment]
I also faced this problem.

**Comment by nmccready** [comment]
Please produce an [MVCE](https://github.com/floridoo/gulp-sourcemaps/wiki/MVCE)

**Comment by nmccready** [comment]
This is old closing until there is feedback against a newer version of this codebase.
