### ISSUE TITLE
Output an external single sourcemap and two transformed files

### ISSUE THREAD

**Issue by mcshaman** [floridoo/gulp-sourcemaps#128]
I currently have a gulp task that looks a bit like this:

```
gulp.task( 'dist', function() {
	
	return gulp.src( './dest/file.js' )
		.pipe( sourcemaps.init( { loadMaps: true } ) )
		.pipe( uglify() )
		.pipe( sourcemaps.write( './' ) )
		.pipe( rename( { suffix: '.min' } ) )
		.pipe( gulp.dest( './src' ) )
		.pipe( gzip() )
		.pipe( gulp.dest('./src') );
	
} );
```

Currently it outputs file.min.js, file.min.js.map, file.min.js.gz, file.min.js.map.gz

What I want it to output is file.min.js, file.min.js.gz, file.map

I have read up on streams to try to work out a solution but I'm struggling to work it out. If anybody could help with a solution I would appreciate it.

**Comment by floridoo** [comment]
`sourcemaps.write()` does not actually write the file, it just adds it to the stream. Your call to `rename` also renames the map file.
