### ISSUE TITLE
Incorrect sourceMappingURL generated

### ISSUE THREAD

**Issue by StuartMorris0** [floridoo/gulp-sourcemaps#131]
Hello,

For our specific setup we create the map file and move it into the same place the minified CSS lives. The issue is that the pre-generated sourceMappingURL is pointing to a network location where the files are referenced, which is therefore the incorrect place when loaded from the web.

Example:
/*# sourceMappingURL=Z:/Custom/Templates/Saber/WWWRoot/content/live/client_rd_base_donotdelete/default/css/styles.min.css.map */

I can see there is an option to prefix this link, but there doesn't appear to be a way for me to say just use the filename and no path.

Thanks

**Comment by jonlil** [comment]
I'm also having simular issue to this.

I'm moving my prod ready files to `dist/scripts/*.js.map`, nginx then serves my dist folder.

So my config is like this

```js

  return gulp.src(['src/**/*.js'])
    .pipe($.sourcemaps.init())
    .pipe($.sourcemaps.write('../dist', {
        'sourceMappingURLPrefix': '/scripts'
    }))
```

my resulting sourceMappingURL
```//# sourceMappingURL=/scripts/../dist/scripts/app-91b1b644.js.map```

What I want
```//# sourceMappingURL=/scripts/app-91b1b644.js.map```

So I solved this by doing this, not sure it's related to your problem
https://github.com/getanewsletter/gulp-sourcemaps/commit/cdbec2e9dfc3cf50f0c184ae0d2ac68ec5ebd84a

**Comment by StuartMorris0** [comment]
Hey @jonlil - Yes I think you are right that is the problem, or similar to what I am after. 

Are you submitting a pull request for the main sourcemaps repo? If not, how do I point my npm node module to your version?

Thanks

**Comment by StuartMorris0** [comment]
Actually my issue is with the line 225 in index.js where the dest file path is included. Because that appears local we want to ignore it.

**Comment by floridoo** [comment]
To help with edge cases like this there is a new option `sourceMappingURL` now, which allows full control over the URL.
