### ISSUE TITLE
How to force sourceMappingURL use absolute paths?

### ISSUE THREAD

**Issue by fedotxxl** [floridoo/gulp-sourcemaps#132]
Hello. `sourceMappingURL` links to map file using relative path (`../../a.js.map`). How to force it to use absolute paths? Adding `sourceMappingURLPrefix` leads to `http://google.com/../a.js.map`

**Comment by mariusGundersen** [comment]
What are the options you provide for the `sourcemaps.write()` method?

**Comment by dellheng** [comment]
+1

this my code
```
    .pipe(sourcemaps.write('../../build', {includeContent: false, sourceRoot: '/',
      sourceMappingURLPrefix: 'http://localhost:8000'}))
    .pipe(gulp.dest(paths.dist + '/js'));
```
this result
//# sourceMappingURL=http://localhost:8000/../build/app.min-42edcc2b10.js.map

**Comment by floridoo** [comment]
This can be done now using the `sourceMappingURL` option.
