### ISSUE TITLE
Source Path Incorrect

### ISSUE THREAD

**Issue by ajmueller** [floridoo/gulp-sourcemaps#133]
We use gulp-sass and gulp-sourcemaps on an open source framework called [Phoenix](https://github.com/connectivedx/Phoenix/) and are currently prepping a new release.  Updating gulp-sass from 1.3.3 to 2.0.1 introduced an issue where the path to source SCSS files for gulp-sourcemaps are missing a directory.

**1.3.3**:
![image](https://cloud.githubusercontent.com/assets/1442179/8241809/4b84a8c0-15c0-11e5-8460-e2df5df5a7b1.png)

**2.0.1**:
![image](https://cloud.githubusercontent.com/assets/1442179/8241813/50467dd4-15c0-11e5-81c4-7d39275af6b9.png)

Note that as of gulp-sass 2.0.1 the `css` directory is missing from the path, thereby loading empty files in the Chrome inspector.  Is this an issue with gulp-sourcemaps or gulp-sass?  If you need additional details or information about how to get our code up and running locally to see for yourself, let me know.

I've posted this issue on [gulp-sass as well](https://github.com/dlmanning/gulp-sass/issues/300).

**Comment by floridoo** [comment]
This seems to be an issue with gulp-sass, not gulp-sourcemaps.
