### ISSUE TITLE
Combine Sourcemaps from 2 different tasks

### ISSUE THREAD

**Issue by zslabs** [floridoo/gulp-sourcemaps#135]
Hi all,
Right now I have two separate tasks -- one for dependency JS files and one for Coffee files (that we write in). Each has their own sourcemap file, but I cannot combine the output because then the sourcemaps for each wouldn't work. Is there a way to combine these sourcemap files to fit within the scope of the two "built" files being combined? The final combined file could happen as a dependency of the JS and Coffee task finishing before it.

**Comment by floridoo** [comment]
Sounds like what you need is `gulp-concat`!
