### ISSUE TITLE
Minifying and renaming disassociates sources pointer

### ISSUE THREAD

**Issue by saaqibz** [floridoo/gulp-sourcemaps#136]
I'm trying to minify and get a source map into a file named 'mycore.min.js' and a map 'mycore.min.js.map.

The problem is that the "sources" attribute does not change and instead directs to a file named 'scripts/app-##HASH##.js'.

mycore.min.js.map:
{"version":3,"sources":["scripts/app-7cb05e4631.js"],"names":["global ...

my gulp build goes as follows
...
    .pipe(jsFilter)
    .pipe($.ngAnnotate())
    .pipe($.sourcemaps.init())
        .pipe($.uglify({preserveComments: false})).on('error', conf.errorHandler('Uglify'))
        .pipe($.rename('mycore.min.js'))
    .pipe($.sourcemaps.write('.'))
...
    .pipe(gulp.dest(path.join(conf.paths.dist, '/')))
    .pipe($.size({ title: path.join(conf.paths.dist, '/'), showFiles: true }));
...

I believe I read that both uglify and rename are supported in the wiki page.

Is there a feature to control the name of the 'sources' so it points to mycore.min.js. In the end I'd like a single min.js and map file made from a bunch of javascript files.

**Comment by nmccready** [comment]
Please see [here](https://github.com/floridoo/gulp-sourcemaps/wiki/MVCE) to make an MVCE.

Since this is an old issue I am closing until there is feedback.
