### ISSUE TITLE
Inconsistent line endings

### ISSUE THREAD

**Issue by gamelover42** [floridoo/gulp-sourcemaps#137]
When the sourceMappingURL comment is added at the end of the output file it always uses the single LF line ending. If the source files are windows line endings then this introduces inconsistent line endings.
This causes Visual Studio and some other editors to warn about inconsistent line endings.

I am using verison 1.5.2

**Comment by floridoo** [comment]
I could make it write `\r\n` on Windows. But I am not sure if all developers on Windows are using `\r\n` as line endings. What do you think?

**Comment by shinnn** [comment]
We can determine whether the file uses `\n` or `\r\n` by using [detect-newline](https://github.com/sindresorhus/detect-newline).

@floridoo If you like the idea, I can submit a pull request.

**Comment by floridoo** [comment]
Sounds good! Thanks!
