### ISSUE TITLE
postcss-import and gulp-sourcemaps

### ISSUE THREAD

**Issue by vkrol** [floridoo/gulp-sourcemaps#138]
Hello!

I try to combine postcss-import and gulp-sourcemaps plugins and I encounter a problem. I created the repository with the example code https://github.com/vkrol/imports-sourcemap
The problem is in the wrong "sources" entry in bundle.css.map https://github.com/vkrol/imports-sourcemap/blob/master/build/bundle.css.map

Please, help me. How i can fix this?

Thanks.

**Comment by floridoo** [comment]
Please try to use sites like StackOverflow for user questions and use Github issues for bug reports only. Thanks
