### ISSUE TITLE
gulp-sass compressed option messing up sourcemaps

### ISSUE THREAD

**Issue by jsheffers** [floridoo/gulp-sourcemaps#149]
I'm using the following to generate Sass and source maps with gulp-sass.  

```
gulp.task('css', function() {
  return gulp.src(config.sass.src)
    .pipe($.sourcemaps.init())
    .pipe($.sass({
      outputStyle: 'expanded', // compressed, expanded
      errLogToConsole: true,
      sourceComments: false,
      includePaths: ['bower_components/foundation/scss', 'bower_components/bourbon/dist', 'bower_components/_foundation4/scss'],
    }).on('error', $.sass.logError))
    .pipe($.sourcemaps.write('./maps'))
    .pipe(gulp.dest(config.sass.dest))
    .pipe($.notify("Updated CSS"));
  });
```

When I use the expanded output style the sourcemaps work fine in browser, but as soon as I use the compressed option it only references the main scss file instead of each individual partial.  Any ideas?

gulp-sass@2.0.4
gulp-sourcemaps@1.5.2

**Comment by glen-84** [comment]
I can confirm this issue.

**Comment by floridoo** [comment]
This sounds like a bug in `node-sass`. `gulp-sourcemaps` just writes the source maps, the plugins are responsible for generating them.
