### ISSUE TITLE
sourceRoot bug

### ISSUE THREAD

**Issue by Maxmaxmaximus** [floridoo/gulp-sourcemaps#150]
```javascript
sourcemaps.write({includeContent: false, sourceRoot: ''})
```

when sourceRoot is empty string then includeContent is true, but must false.
I want to place the card in the same folder as the source, How can I do it?

make to check for undefined and null
not this:
```javascript
if(sourceRoot)
```
like this:
```javascript
if(sourceRoot != null)
```

**Comment by Maxmaxmaximus** [comment]
this helped me here, but it is not a solution: 
```javascript
sourcemaps.write({includeContent: false, sourceRoot: '../build'}) 
//or 
sourcemaps.write('../build') 
```

**Comment by floridoo** [comment]
Not sure if I understand what you mean...
If you want to write the source map to the same directory as the destination files, use `sourcemaps.write('.')`.

**Comment by Maxmaxmaximus** [comment]
Yes but why empty string is not alias to '.' ?
