### ISSUE TITLE
Breaking change? Please follow semver

### ISSUE THREAD

**Issue by FGRibreau** [floridoo/gulp-sourcemaps#154]
[This is a breaking change right?](https://github.com/floridoo/gulp-sourcemaps/commit/ad99c9637187035ea59ad006d2d0794e1b198710#diff-40dfb1c53004f1488cbe6eb300b286ddR298)

Because sourcemaps won't be updated if a file already exist, so gulp-sourcemaps should have been upgraded to 2.0.0 right ?

A changelog would be nice :)

**Comment by floridoo** [comment]
This was a bugfix. Overwriting existing source maps with an empty one was never an intended or documented behavior.
