### ISSUE TITLE
Change source URL for some files

### ISSUE THREAD

**Issue by Francisc** [floridoo/gulp-sourcemaps#162]
Hello,

Given this file structure:

```
node_modules/normalize.css/normalize/css
css/style.css
```

Is it possible to "lie" about where normalize.css is located and have the sourcemap say it's also inside the CSS folder?

**Comment by Francisc** [comment]
*ping*

**Comment by konclave** [comment]
mapSources option?

**Comment by nmccready** [comment]
@konclave is correct , You would only run your custom mapSources if the filePath matched for `node_modules/normalize.css/normalize/css`. This would probably be easier by using `gulp-if` to test the one file and force the write specifically for that.

mapSources

This option gives full control over the source paths. It takes a function that is called for every source and receives the default source path as a parameter.

Example:
```
var _if = require("gulp-if")
var pathToFake = "node_modules/normalize.css/normalize/css";

gulp.task('javascript', function() {
  var stream = gulp.src('src/**/*.js')
    .pipe(sourcemaps.init())
      .pipe(plugin1())
      .pipe(plugin2())
    .pipe(_if(pathToFake + "*", sourcemaps.write('../maps', {
      mapSources: function(sourcePath) {
        sourcePath = sourcePath.replace(pathToFake, "");
       //fake path
        return '../src/' + sourcePath;
      }
    }))
    .pipe(_if("!"+ pathToFake + "*", sourcemaps.write('../maps) //normal things not to fake
    .pipe(gulp.dest('public/scripts'));
});
```
