### ISSUE TITLE
Error message stops file watcher from running

### ISSUE THREAD

**Issue by josh18** [floridoo/gulp-sourcemaps#165]
Usually when I have an error in my less compilation it shows an error but the file watcher (gulp-livereload) continues working. However now that I have included sourcemaps when I make an error in my less files it outputs:
```
Potentially unhandled rejection [2] Error in plugin 'gulp-less'
```
and stops the file watcher from working. My gulpfile looks something like this:
```js
gulp.task('less', function() {
    return gulp.src('*.less')
        .pipe(sourcemaps.init())
        .pipe(concat('styles.css'))
        .pipe(less())
        .pipe(sourcemaps.write('.'))
        .on('error', function(err) {
            gutil.log(err);
            this.emit('end');
        })
        .pipe(gulp.dest('css/'));
});
```
Any ideas how I can get around this? Tried setting debug to false but it doesn't seem to help.

**Comment by marvinhagemeister** [comment]
I'm not at a pc at the moment, but the issue seems to be that gulp-less throws an exception and that this exist the stream without calling `this.emit('end')`. Either attach attach a specific error handler to `less()` or have a look into `gulp-plumber` which can catch all excceptions for the whole stream.

**Comment by josh18** [comment]
Oh, maybe my order is wrong and it should be
```js
.pipe(less())
.on('error', function(err) {
    gutil.log(err);
    this.emit('end');
})
.pipe(sourcemaps.write('.'))
```
?

**Comment by marvinhagemeister** [comment]
That should work as well.

**Comment by josh18** [comment]
Confirmed it works, thanks for your help.
