### ISSUE TITLE
sourcemaps and minify-css

### ISSUE THREAD

**Issue by deni35** [floridoo/gulp-sourcemaps#166]
I wrote the task:

```
return gulp.src('src/less/**/*.less')
            .pipe(sourcemaps.init())
            .pipe(less())
            .pipe(sourcemaps.write('/'))
            .pipe(gulp.dest('www/css/'))

            .pipe(minifyCSS())
            .pipe(rename({
                suffix: '.min'
            }))
            .pipe(gulp.dest('www/css/'));
```

As a result I have an empty css.min.map files.
Maybe there way to ignore min.css files or it is a bug?
Also it is strange because my css file ends on min.css. Not css.min!

Also I notice that sourcemaps.write() (without args) doesn't work.

**Comment by jaminroe** [comment]
I'm having a similar issue. I want to prevent gulp from creating a source map for the minified CSS file. There's an option for 'sourceMap: false' but it doesn't work. I'm blaming both '.pipe(sourcemaps.init())' and '.pipe(sourcemaps.write('./'))'

See here: https://github.com/jakubpawlowicz/clean-css/issues/716

**Comment by phated** [comment]
Closing this because it is a problem with those plugins, not gulp-sourcemaps.
