### ISSUE TITLE
Debugging variables not working with sourcemaps + uglify

### ISSUE THREAD

**Issue by fernandoneira** [floridoo/gulp-sourcemaps#168]
I have the following gulp task for bundling javascript:

```
gulp.task('js', function () {
    return gulp.src(paths.js)
        .pipe(sourcemaps.init())
        .pipe(uglify())
        .pipe(concat('bundle.min.js'))
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest('dist'));
});
```

When I run this in the Chrome dev tools, sourcemaps are found and breakpoints work, **but variables can't be debugged**.

Take this example chunk of angular code:

```
iarApp.config(['$animateProvider', function ($animateProvider) {
    $animateProvider.classNameFilter(/angular-animate/);
}]);
```

If I add a breakpoint to see the value of `$animateProvider`, I get the following:

[![enter image description here](http://i.stack.imgur.com/oISm0.png)](http://i.stack.imgur.com/oISm0.png)

But if I turn off variable mangling in Uglify:

```
.pipe(uglify({ mangle: false }))
```

Then it works:

[![enter image description here](http://i.stack.imgur.com/hzdEX.png)](http://i.stack.imgur.com/hzdEX.png)

So it seems that the gulp-sourcemaps plugin can't follow up variables after Uglify mangles the names.

Can anyone else get the same issue and/or know a solution?

**Comment by phil-lgr** [comment]
+1 I also encounter the same problem. @fernandoneira, when you add a break point does it anchor exactly where you put it or does it stop in minify code ?

**Comment by fernandoneira** [comment]
@phil-lgr I don't have problems anchoring in the source, that may be something else going with your source.

The variable mangling is, as I found out, a limitation of the current source map spec. It just doesn't support symbol mapping as I mentioned here: http://stackoverflow.com/questions/33913641/debugging-variables-not-working-with-gulp-sourcemaps-uglify/34872450#34872450

**Comment by rafaelcamargo** [comment]
@fernandoneira I have just tried your workaround `{ mangle: false }` and works fine. Thanks man!

**Comment by nmccready** [comment]
Can this be be closed or does this need to be dug unto more? Will need to copy the workflow above into integration.js

**Comment by phated** [comment]
This is a sourcemap problem, not a gulp-sourcemaps issue.
