### ISSUE TITLE
Throws error in Chrome: Uncaught SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by logesh-kumar** [floridoo/gulp-sourcemaps#170]
I am creating an external sourcemap and referring it in my index.html file. The minified script is running fine. But the sourcemap file throws the below error in Chrome(47).

````
Uncaught SyntaxError: Unexpected token :
````
Here is how I am referring the source map in my index.html page

````
 <script type="text/javascript" src="/ccg/resources/js/build/main.min.js"></script>
 <script type="text/javascript" src="/ccg/resources/js/build/main.min.js.map"></script>
````

I am using this configuration in my gulpfile.js.

```javascript
gulp.task('ccgscripts', function() {
  gulp.src(['resources/js/vendor_scripts/jquery-1.11.3.js',
  'resources/js/vendor_scripts/jquery-ui-1.10.4.js',
  'resources/js/vendor_scripts/underscore.js',....])
    .pipe(sourcemaps.init())
    .pipe(concat('ccgScript'))
    .pipe(stripDebug())
    .pipe(uglify())
    .pipe(sourcemaps.write('./'))
    .pipe(rename({suffix: '.min.js'}))
    .pipe(gulp.dest('resources/js/build/'));
}); 
````
Can anyone provide some insight on this?

**Comment by floridoo** [comment]
You are trying to include the source map as javascript:
`<script type="text/javascript" src="/ccg/resources/js/build/main.min.js.map"></script>`.
The browser finds the source map based on the special comment in the javascript source file, you are not supposed to include it like this.
