### ISSUE TITLE
Alternative to gulp-strip-debug for Javascript

### ISSUE THREAD

**Issue by jonathan-soifer** [floridoo/gulp-sourcemaps#171]
Hi,

Currently gulp-strip-debug doesn't seem to be compatible with gulp-sourcemaps.

I've looked over the compatible options on the wiki but wasn't able to find any other package to replace it:

Are there any other options to remove console and debugger statements from JavaScript code that are compatible with gulp-sourcemaps?

Thank you :)

**Comment by floridoo** [comment]
No, none I'm aware of.

Btw: please use the Github issues for actual bug reports. There's other places (e.g. StackOverflow) where your question will probably get more answers. Thanks
