### ISSUE TITLE
Using a sourcemap as the flag for whether to generate sourcemaps in plugins is somewhat limiting.

### ISSUE THREAD

**Issue by kkerchmar** [floridoo/gulp-sourcemaps#173]
Please consider the following example:    

    var sourcemaps  = require('gulp-sourcemaps');

    gulp.task('javascript', function() {
        gulp.src('src/**/*.js')
            .pipe(sourcemaps.init())
            .pipe(someplugin())
            .pipe(sourcemaps.write())
            .pipe(gulp.dest('dist'));
    });

All files processed will have a `file.sourceMap` property set by `sourcemaps.init()`. `someplugin` will check the `file.sourceMap` property to see if a sourcemap should be generated for that file. `someplugin` will later call `vinyl-sourcemaps-apply`, where the same property will be checked for again; if it exists, a merge of the existing sourcemap will occur; if it does not exist, the new sourcemap will simply be set. 

I conclude that in the context of `gulp-sourcemaps`, all sourcemaps will undergo a merge operation with either the empty source map that is created by `gulp-sourcemaps` or a sourcemap that was already merged prior in the same chain. There is no way at present to cause `vinyl-sourcemaps-apply` to set the sourcemap rather than merge with the provided empty sourcemap.

This would be okay, except there are known issues (and possibly unknown issues) with sourcemap merging. `vinyl-sourcemaps-apply` currently creates a sourcemap that is the minimum of both inputs. This is not necessarily ideal, as has been recognized in the issues in the `vinyl-sourcemaps-apply` project. I am currently experiencing an issue where `sass` is producing a valid source map, but the merge operation is producing an invalid source map. 

I would prefer there to be the option of directly writing the source map rather than merging it if there is only going to be a single code-transforming step anyway. For instance, `sass` is taking care of compilation, imports, and minification for me. I have no need to merge additional maps together in this case, and the limitations of sourcemap merging could be avoided in this particular case.

If there were a flag on each file such as "shouldGenerateSourceMaps" that were set by `gulp-sourcemaps`.init(), plugins could check that flag instead of there needing to be an empty source map to begin with. That way, when there is only a single map-generating pipe step in the gulp configuration for a task, `vinyl-sourcemaps-apply` would see no existing sourceMap property on the file, and would thus set the sourcemap property rather than merging the existing map with the new one.

Unfortunately, this would be a breaking change that all plugins would need to adjust for if it were implemented. 

Was there relevant intention behind not doing this in the first place that I'm overlooking?

An alternative that is non-breaking but is less ideal could be to include a flag on each file to signal that new sourcemaps should overwrite rather than be merged with existing sourcemaps. `gulp-sourcemaps` could take in an option that specifies whether to use merge or overwrite, and it could set this flag within the init() call. `vinyl-sourcemaps-apply` would then also need to be modified to look for this flag and act accordingly.

**Comment by floridoo** [comment]
`vinyl-sourcemaps-apply` now doesn't try to merge with an empty source map (like the one generated by `sourcemaps.init()`) anymore. See https://github.com/floridoo/vinyl-sourcemaps-apply/commit/30320c97c112f44ccba02dd73ce5bed1ad4361de.
Does this solve your issue?

**Comment by kkerchmar** [comment]
This does solve my issue and I appreciate the pragmatism in your solution.
