### ISSUE TITLE
Adding option for indention / line-breaks

### ISSUE THREAD

**Issue by McShelby** [floridoo/gulp-sourcemaps#176]
For a rather big project I bundle all my js sources and finally generating sourcemaps into one separate file. Usually I do not ship them but keep them stored in my repository. 

Sadly, a single change in one of my sourcefiles causes the whole sourcemap file to be completely rewritten. Diffs on this file are then useless and the changeset gets rather big.

By exposing the third parameter of JSON.stringify() as an option to the sourcemaps.write() function, I'ld be able to control indention / line-breaks.

**Comment by nmccready** [comment]
Sorry this has been such a long time. But could you please make a small example to expose your problem. Or make a PR with unit / integration tests showing off the feature you desire. 

Closing until there is feedback.

**Comment by donquixote** [comment]
Hello!
I cannot reopen this one, so I created #374
