### ISSUE TITLE
The problem with Russian encoding in coffeescript

### ISSUE THREAD

**Issue by slavikse** [floridoo/gulp-sourcemaps#181]
Input:

```
# Проблема с Русской кодировкой :(
console.log 'Проблема с Русской кодировкой'
```

Output:

```
# ÐŸÑ€Ð¾Ð±Ð»ÐµÐ¼Ð° Ñ Ð ÑƒÑÑÐºÐ¾Ð¹ ÐºÐ¾Ð´Ð¸Ñ€Ð¾Ð²ÐºÐ¾Ð¹ :(
console.log 'ÐŸÑ€Ð¾Ð±Ð»ÐµÐ¼Ð° Ñ Ð ÑƒÑÑÐºÐ¾Ð¹ ÐºÐ¾Ð´Ð¸Ñ€Ð¾Ð²ÐºÐ¾Ð¹'
```

<img src="https://habrastorage.org/files/b5b/5a8/d70/b5b5a8d70fa84ddd8ee160ad88188b44.png"/>

<img src="https://habrastorage.org/files/960/a9d/515/960a9d515a0a4f96a673da7824fa06e0.png"/>

**Comment by nmccready** [comment]
You need to produce a minimal example on how to produce your problem. Add something to a unit test and or integration test in the current codebase. OR make a small gulp example zip / tar file.

I would first also check to see if this is an issue in https://www.npmjs.com/package/source-map as this is the main component of this project. Also this could be the coffee compiler having issues as well.

Closing until there is feedback.
