### ISSUE TITLE
In Chrome Canary, //@ sourceURL and //@ sourceMappingURL are deprecated

### ISSUE THREAD

**Issue by jfurrow** [floridoo/gulp-sourcemaps#182]
In Chrome Canary, I'm receiving warnings about the deprecated syntax. I'm not sure if you're concerned about Canary, but it might be worth considering.

![](http://cl.ly/3T3K28421i1l/Screen%20Shot%202016-02-24%20at%2011.48.43%20AM.png)

**Comment by floridoo** [comment]
`gulp-sourcemaps` doesn't use the old form of source map comments (and btw never did so).

**Comment by jfurrow** [comment]
Sorry, this was caused by a different plugin entirely...
