### ISSUE TITLE
Imported SCSS within rule doesn't get mapped

### ISSUE THREAD

**Issue by dgirgenti** [floridoo/gulp-sourcemaps#185]
I have the following valid (though not preferred) SCSS:

    .foo {
        @import "bar";
    }

**What happens**
Everything coming from `bar.scss` is mapped to the `.foo` rule (Line 1 in this example SCSS), and Chrome doesn't bother delving any further into `bar.scss`'s mappings.

**What should happen**
`bar.scss` should be sourcemapped as normal.

--------

As expected, when I remove the `@import "bar";` from the `.foo` rule, all the sourcemaps from `bar.scss` do work as intended, so I know the issue does not lay there.

Forgive me if this ticket is a duplicate; I could not find anything related to this specific issue, though it may be similar to #161

**Comment by Iazel** [comment]
Hello, I suggest you to install the latest versions of `gulp-sass` and `node-sass`. For more info:
https://github.com/floridoo/gulp-sourcemaps/issues/161#issuecomment-199779155

**Comment by dgirgenti** [comment]
@Iazel thanks, that did fix it. I guess this is an issue with the current version of gulp-sass and not gulp-sourcemaps.
