### ISSUE TITLE
Can you release the master branch version on npm ?

### ISSUE THREAD

**Issue by djflex68** [floridoo/gulp-sourcemaps#186]
I need the changes made about sourceRoot paths.

**Comment by zgmnkv** [comment]
+1

**Comment by d3viant0ne** [comment]
@floridoo - Same request as above. 

Currently to make typescript coverage work you need to run sourcemaps#master & until yesterday remap-istanbul#master ( 0.6.1 landed yesterday ).

The TypeScript coverage for Angular2-material can't be implemented with a dep on master which blocks that feature until a new tag is cut.

**Comment by jp7677** [comment]
I concur on that. I'm using head@master too since I need the (perfectly working) mapSources option that is available on master only. Could you please publish a release?

**Comment by floridoo** [comment]
Published as v2.0.0-alpha on npm, some things are still missing for 2.0.0

**Comment by d3viant0ne** [comment]
@floridoo - Appreciated, thank you
