### ISSUE TITLE
write option destPath is not available

### ISSUE THREAD

**Issue by SetTrend** [floridoo/gulp-sourcemaps#189]
The `destPath` option has been added to `sourcemaps.write()` three months ago but until now it doesn't seem to be available when downloading the latest package (v1.6.0).

Why?

**Comment by SetTrend** [comment]
Never mind. By some reason v1.5.2 was downloaded although I requested v1.6.0

**Comment by PhilippCh** [comment]
The option seems to be available, but I can confirm that write("xxx") doesn't output any external sourcemaps to directory XXX.

**Comment by phated** [comment]
Published now but the option doesn't cause a filesystem write (that's against gulp guidelines).
