### ISSUE TITLE
Syntax change in Chrome Beta

### ISSUE THREAD

**Issue by simonlast** [floridoo/gulp-sourcemaps#190]
When I load a sourcemap in Chome Beta, I get this message: 

    '//@ sourceURL' and '//@ sourceMappingURL' are deprecated, please use '//# sourceURL=' and '//# sourceMappingURL=' instead.

**Comment by zephyrweb** [comment]
Most likely this is coming from upstream. The syntax changed a long time ago. I'm on beta and canary (nightly).

**Comment by floridoo** [comment]
`gulp-sourcemaps` uses the correct new syntax. The error message must come from another plugin.
