### ISSUE TITLE
source maps not creating external file node v6

### ISSUE THREAD

**Issue by retep007** [floridoo/gulp-sourcemaps#197]
Problem: I need to create sourcemaps into external files, but they keep inserting to original file.

Code:
`return gulp.src('dist/tom3/*.js')
    .pipe(sourcemaps.init({loadMaps: true}))
    .pipe(uglify({
         mangle: true,
         compress: true
     }))
    .pipe(sourcemaps.write('./map', { sourceRoot: 'css-source' }))
    .pipe(gulp.dest('dist'));`

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
