### ISSUE TITLE
"mapSources" .write() option ignored / never called

### ISSUE THREAD

**Issue by mattflix** [floridoo/gulp-sourcemaps#199]
The "mapSources" callback function does not seem to be called when passed as a .write() option.

For example, I included the following snippet in one of gulpfile streams in which sourcemaps are generated (for example, from Babel):

```
sourcemaps.write('.', {
    mapSources: function(path) {
        console.log('called for ' + path);
        return 'hello' + path;
    }
})
```

New map files were definitely generated, but I saw no evidence that my mapSources function was ever invoked.

I saw none of the expected console output, and none of the source paths (in the final generated map files) were prefixed with "hello".

**Comment by mattflix** [comment]
Btw, the only reason I'm trying to use mapSources is because gulp-sourcemaps doesn't seem to emit useful "sources" values in the source maps.

I'm using Babel.  The Babel CLI with the sourceMaps=true option creates working source maps.  But, in Gulp, I am unable to reproduce the same output using gulp-babel or gulp-sourcemaps.  Seems like it should be trivial, but after 5 hours I gave up and submitted this issue.

**Comment by cspeer** [comment]
yeah, I'm having the same problem! +1

**Comment by jgrund** [comment]
The issue is that code does not exist in `gulp-sourcemaps@1.6.0` (Currently the latest version), even though it's in the cooresponding readme.

**Comment by jgrund** [comment]
It is in `gulp-sourcemaps@2.0.0-alpha`

**Comment by cspeer** [comment]
Nice! Do you have a roadmap here? :)

**Comment by freask** [comment]
I have same problem with all write options:

```
.pipe(sourcemaps.write('../_maps', {
				charset: 'win1251',
				mapSources: function(path) {
					console.log('called for ' + path);
					return path;
				},
				mapFile: function(mapFilePath) {
					// source map files are named *.map instead of *.js.map
					console.log(mapFilePath);
					return mapFilePath.replace('.js.map', '.map');
				}
			}))
```

Encoding not changes, mapSources and mapFile not called!
And I'm not see any strings about these options in the gulp-sourcemaps/index.js

**Comment by JCBradley91** [comment]
+1

mapFile never called in gulp-sourcemaps/index.js

**Comment by eugenio4** [comment]
+1, mapFile never called in gulp-sourcemaps

**Comment by wolfy1339** [comment]
This issue has plagued me too

**Comment by giespaepen** [comment]
+1

**Comment by kofrasa** [comment]
Any update on this issue?

**Comment by HalfLegend** [comment]
+1

**Comment by stevomccormack** [comment]
Mee too.

**Comment by phated** [comment]
Use the new gulp-sourcemaps.  Locking.
