### ISSUE TITLE
Error: [Bower Component] is not in the SourceMap.

### ISSUE THREAD

**Issue by philipbenton** [floridoo/gulp-sourcemaps#200]
I am receiving the following error:

Error: "/components/include-media/dist/_include-media.scss" is not in the SourceMap.

Any ideas how I can include Bower components in my SourceMap? The file in question is imported into my styles.scss file:

``` css
@import
  '../../../components/include-media/dist/include-media';
```

My Gulp task looks like this:

``` js
var cssTask = function() {
  return gulp.src(paths.src)
    .pipe(gulpif(!global.production, sourcemaps.init()))
    .pipe(sass(gulpif(!global.production, config.tasks.css.sass.default, config.tasks.css.sass.production)))
    .pipe(autoprefixer(config.tasks.css.autoprefixer))
    .pipe(size({
      title: 'stylesheets',
      showFiles: false
    }))
    .pipe(gulpif(!global.production, sourcemaps.write()))
    .pipe(gulp.dest(paths.dest))
    .pipe(browserSync.stream())
}
```

**Comment by stevenvachon** [comment]
I'm getting this with *.less files within *node_modules/*

**Comment by stevenvachon** [comment]
@philipbenton here is a temporary solution: https://github.com/floridoo/gulp-sourcemaps/issues/174#issuecomment-195033838

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
