### ISSUE TITLE
Broken source map file after updating to OSX 10.11.5 (15F34)

### ISSUE THREAD

**Issue by Safi1012** [floridoo/gulp-sourcemaps#201]
After installing the newest Mac Update: OSX 10.11.5 (15F34) the ‘gulp-sourcemaps’ plugin seems not to work correctly with TypeScript files.

In my case the ‘gulp-sourcemaps’ plugin generates an inlined source map file which contains all my JavaScript files. Unfortunately the generated source map file seems to be broken. 

The linked TypeScripts files in the source map are empty when debugging in my Browser. (I tested Chrome, Firefox and Safari)

Safari for example gives me the following error for a TypeScript file:

`Cannot GET /source/components/feedbackEvaluation/feedbackEvaluationDirective.ts`

I included in the attachments my generated source map file.

[tsc.js.zip](https://github.com/floridoo/gulp-sourcemaps/files/289154/tsc.js.zip)

**Comment by phated** [comment]
An OS update wouldn't effect this. Support questions should be directed to StackOverflow.
