### ISSUE TITLE
Broken sourcemaps with Chrome 51.x

### ISSUE THREAD

**Issue by puzzfuzz** [floridoo/gulp-sourcemaps#202]
Looks like this is related to this issue open against Chromium: 

https://bugs.chromium.org/p/chromium/issues/detail?id=611328

Only listed solution is stripping BOM from the sourcemap, which gulp-sourcemaps already does. However, I noticed that it uses strip-bom 2.x; perhaps upgrading to 3.x would solve this?

**Comment by azzlack** [comment]
I have the same issue. Sourcemap works fine in Firefox, but it either doesnt load in Chrome 51 or loads with the wrong file content (I get the content of another source file)

**Comment by nmccready** [comment]
Please try against master and see if this is still an issue. Will re-open depending on feedback.
