### ISSUE TITLE
this reference not aliased correctly inside a jquery event callback

### ISSUE THREAD

**Issue by brandonwittwer** [floridoo/gulp-sourcemaps#207]
It appears that the 'this' reference isn't being mapped correctly when dealing with a jquery event callback.  

I've got a snippet of code which approximately looks like this:
`
let _listener;
export class DataTableComponent{
    table;
    attached(){
        this.table = $(this.datatablecomponent).DataTable(this.options);
        this.setupButtonVisibility();
    }
    setupButtonVisibility(){
       _listener = this.table.on( 'select', ()=>{
            var selectedRows = this.table.rows( { selected: true } ).count();
            ///do some things
        });
    }
}
`

When a breakpoint is set on the first line inside the select callback 'this' is the dom object of the fired event.  It should instead be the class instance and should have a table property.

I glance at the generated code:

`
}, {
            key: 'setupButtonVisibility',
            value: function setupButtonVisibility() {
                var _this = this;

```
            if (_listener) {
                _listener.off();
            }
            _listener = this.table.on('select', function () {
                var selectedRows = _this.table.rows({ selected: true }).count();
```

`
and notice that the _this reference should be the instance of the class property in the background.  I hit it in the console and see that it's correctly assigned.  But hitting 'this' in the console or a watch statement still is pointing to the dom object.

**Comment by phated** [comment]
This is a general sourcemap issue, not a gulp-sourcemaps issue.
