### ISSUE TITLE
SASS files don't get mapped

### ISSUE THREAD

**Issue by smartm0use** [floridoo/gulp-sourcemaps#212]
Since i have to process SASS files to CSS for my Angular2 app, i created the following task:

```
gulp.task('create:styles', function(cb) {
    return gulp.src('src/app/**/*.scss')
	             .pipe(sourcemap.init())
	             .pipe(sass().on('error', sass.logError))
	             .pipe(sourcemap.write())
	             .pipe(gulp.dest(paths.dist + '/app/'));
	});
```

As you can see i'm using sourcemaps plugin to map source files of styles.

Do you know why i can't see the source files (`.scss`) in the inspection tools of browsers? What's wrong with sourcemaps plugin?

**Comment by gfdesign** [comment]
Same problem here :|

**Comment by smartm0use** [comment]
The problem depends on Angular core code. I think it has been fixed a couple of days ago: https://github.com/angular/angular/commit/bc6d1c87a644402c2cdb9d6630bfe957eda1dc26

**Comment by gfdesign** [comment]
I don't use Angular.
As soon I can, I'll be back to this thread with a simple configuration in order to you see if I have something wrong.
Regards

**Comment by gfdesign** [comment]
Hi there. Me again.
I am not able to make it work this simple gulpfile.js

```
var gulp = require('gulp');
var sass = require('gulp-sass');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('default', function() {
  gulp.src('src/**/*.scss')
  .pipe(sourcemaps.init())
  .pipe(sass())
  .pipe(sourcemaps.write('.'))
  .pipe(gulp.dest('.'));
});
```

Basically, this does not generate the sourcefile in any place. The rest works as I expect.
What am I doing wrong?
I'd appreciate any help.
Thanks

**Comment by gfdesign** [comment]
Hi again. I think I've found my problem.
First, my gulpfile.js was wrong. This is the corrected version:

```
var gulp = require('gulp');
var sass = require('gulp-sass');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('default', function() {
  gulp.src('src/**/*.scss')
  .pipe(sourcemaps.init('.'))
  .pipe(sass())
  .pipe(sourcemaps.write('.'))
  .pipe(gulp.dest('.'));
});
```

Second, I had to active in my Firefox browser in developer options this one:
![capture](http://i.imgur.com/as02kk4.jpg)

I was dealing with this issue for days. I hope it helps someone else.
Best regards

**Comment by smartm0use** [comment]
Here, on Chromium 52.0.2743.116 still not work:

![dd](https://cloud.githubusercontent.com/assets/5399265/18480323/96265874-79d8-11e6-97e5-8b8bd37fbf1a.png)

I have no `.scss` file in the source folder...
