### ISSUE TITLE
Source map generation is very slow when using less

### ISSUE THREAD

**Issue by jongunter** [floridoo/gulp-sourcemaps#215]
I have about 30 or so JS files that I'm bundling and for which I'm generating source maps. The task takes less than a second on Windows.

Additionally, I have about 5 LESS files that I'm compiling and then bundling together.  The task takes a little over a second. However, when I add source maps into the process, the task runs for _over 20 seconds_ on Windows.

Here's my task in question:

``` js
gulp.task('css', function () {

   // Reads from a config file
    var bundles = getUpdatedBundleConfig();

    return gulp
        .src(bundles.css, { base: './' })
        .pipe(sourcemaps.init())
        .pipe(less())
        .pipe(concat('all.min.css'))
        .pipe(sourcemaps.write({includeContent: false, sourceRoot: '../../' }))
        .pipe(gulp.dest(cssBuildPath));
});
```

Any leads on what could be going wrong?

**Comment by Corliosity** [comment]
@jongunter have you found any resolution to this issue?  I am having a similar problem compiling LESS using gulp-less and sourcemap.

Thanks!

**Comment by RyKilleen** [comment]
@jongunter @Corliosity We are also experiencing this. Any chance anyone's found a resolution?

**Comment by jongunter** [comment]
No solution yet, but I have a workaround: Rather than generating sourcemaps in a dev environment, I've switched to using gulp-inject to add the each JS file, as script tags, to our index.html. With LESS, I embed `less.js` in the page and let it do the compilation on-the-fly.

For a non-dev build, it's not a big deal to have sourcemaps take a long time, since these are only done when releasing to a server.

**Comment by jongunter** [comment]
Just a note...my solution above doesn't really allow you to map compiled CSS back to its LESS files, but I really care more about source-mapping JavaScript.

**Comment by nmccready** [comment]
Someone needs to produce a solid example in here https://github.com/floridoo/gulp-sourcemaps/blob/master/test/integration.js#L25-L47 . Duplicate that and and I can run it. It is possible that your glob is too loose and looking at too many files. Example '**/*.less' will dig into node_modules . I will add a basic gulp-less integration and see what I get for speed. But ultimately I need something solid from you guys.

**Comment by nmccready** [comment]
I added the following integration spec which pull in a single less file along with all of bootstrap (many files). Anyway the test succeeds within 1.5 seconds. I need more examples of this being slower to proceed further.  Closing until that is provided.

**Comment by nmccready** [comment]
Also to run the integration spec itself `./node_modules/.bin/tape ./test/integration.js`
