### ISSUE TITLE
loadMaps true seams to confuse the browser debugger tools

### ISSUE THREAD

**Issue by justinledouxweb** [floridoo/gulp-sourcemaps#216]
I am compiling ES6 code with browserify and a babel transform. In the output, I am using `sourcemaps.init({ loadMaps: true })` which gives me a representation of the code as I wrote it, into the browser's dev tool.

That said because Babel transpiles the code using different variable or method names (`this` become `_this` for example), when I try to find out the value of `this` in the console (using a debugger in the code), I get underfined, since `this` is really `_this`.

Is it a question of setup or perhaps intended? Or shouldn't the browser be able to map what I see and type in the console to the transpiled values that are truly in the code?

Here is my gulp file:

```
function buildScript(appName, build) {
  let bundler = browserify({
    entries: config.browserify[appName].src,
    debug: true,
    cache: {},
    packageCache: {},
    fullPaths: config.environment !== 'prod',
  }, watchify.args)
  .transform(babel)
  .transform(stringify, {
    appliesTo: { includeExtensions: ['.html'] },
    minify: true,
  });

  if (!build) {
    bundler = watchify(bundler);
    bundler.on('update', () => {
      rebundle();
    });
  }

  function rebundle() {
    const stream = bundler.bundle();

    gutil.log('Rebundle...');

    return stream.on('error', handleErrors)
      .pipe(source(`${appName}.js`))
      .pipe(buffer())
      .pipe(gulpif(config.environment !== 'prod', sourcemaps.init({
        loadMaps: false,
      })))
      .pipe(gulpif(config.environment === 'prod', uglify({
        mangle: true,
      })))
      .pipe(gulpif(config.environment !== 'prod', sourcemaps.write('./')))
      .pipe(gulp.dest(config.browserify[appName].dest))
      .pipe(gulpif(!build, browserSync.stream({ once: true })));
  }

  return rebundle();
}
```

**Comment by nmccready** [comment]
Closing this unless there is a smaller reproducible example made.

**Comment by nmccready** [comment]
Might be related or help your problem #248
