### ISSUE TITLE
//@ sourceURL' and '//@ sourceMappingURL' are deprecated

### ISSUE THREAD

**Issue by throrin19** [floridoo/gulp-sourcemaps#220]
Hello, I think the sourcemap library must to be upgraded to use the new sourceUrl format. In Chrome, I have this warning : 

```
'//@ sourceURL' and '//@ sourceMappingURL' are deprecated, please use '//# sourceURL=' and '//# sourceMappingURL=' instead.
```

**Comment by shinnn** [comment]
Duplicate of https://github.com/floridoo/gulp-sourcemaps/issues/182

**Comment by nmccready** [comment]
@shinnn since the dupe is closed, can this be closed?
