### ISSUE TITLE
Why 2.0? If so, document why.

### ISSUE THREAD

**Issue by Pszek** [floridoo/gulp-sourcemaps#225]
I know it is in alpha stage, but could someone provide me with info whas's changed?

**Comment by nmccready** [comment]
@Pszek I am not entirely sure yet as I have just begun digging into this. One thing for sure that is a possible break is the latest version of vinyl. See https://github.com/floridoo/gulp-sourcemaps/blob/master/test/init.js#L286-L287

**Comment by nmccready** [comment]
@floridoo any other ideas?

**Comment by nmccready** [comment]
In comparing https://github.com/floridoo/gulp-sourcemaps/compare/v1.6.0...v2.0.0-alpha it appears that there are no breaking changes. I am trying to confirm the motivators for 2.X . If there are no breaking changes then I see no reason to not release 1.7 .

**Comment by nmccready** [comment]
@shinnn @floridoo @zacronos

**Comment by zacronos** [comment]
Agreed, it appears @floridoo was beginning to think about some things like an upgrade to `vinyl` 2.X which could have involved breaking changes for `gulp-sourcemaps` as well -- but no such changes have actually been committed yet.  It should be safe to release v1.7.

**Comment by nmccready** [comment]
Closing and marking milestone as 1.7

**Comment by shinnn** [comment]
Sorry for a bit late response. I agree with v1.7 too.

**Comment by nmccready** [comment]
LOL here is why https://github.com/floridoo/gulp-sourcemaps/commit/2d8c319a5c8477a6e2f27ce42009b0109faa7421#commitcomment-19367684
