### ISSUE TITLE
Sourcemaps that ignore sass partials 

### ISSUE THREAD

**Issue by Pyrothraxis** [floridoo/gulp-sourcemaps#226]
I've read through the documentation and can't seem to find an option for this. For example if I @import a partial with variable/mixins/extends etc and then compile sass(gulp-sass) when I write the sourcemap the source is slightly off. 

If there is an option for this then apologies in advance for wasting your time.

**Comment by nmccready** [comment]
Please make something reproducible via an integration test.

**Comment by nmccready** [comment]
No response, killing this.
