### ISSUE TITLE
Unexpected token ) after latest update (1.7.2)

### ISSUE THREAD

**Issue by GasparMDQ** [floridoo/gulp-sourcemaps#236]
I've this error message after the latest update (f51b931c831ed405e535025aea24dafdffb11e11)

`//node_modules/lcov-result-merger/node_modules/vinyl-fs/node_modules/gulp-sourcemaps/index.js:38`
    `debug(() => {return options;});`
`SyntaxError: Unexpected token )`
   `at exports.runInThisContext (vm.js:73:16)`
   `at Module._compile (module.js:443:25)`
   `at Object.Module._extensions..js (module.js:478:10)`
   `at Module.load (module.js:355:32)`
    `at Function.Module._load (module.js:310:12)`
   `at Module.require (module.js:365:17)`
    `at require (module.js:384:17)`
    `at Object.<anonymous> (//node_modules/lcov-result-merger/node_modules/vinyl-fs/lib/src/index.js:8:18)`
    `at Module._compile (module.js:460:26)`
    `at Object.Module._extensions..js (module.js:478:10)`

The token referred is the first closing round bracket: debug((**)** => {return options;});

I'm using node v0.12.7

Replacing all 
`() => {<return here>}`
with
`function() {<return here}`
seems to fix it.

I'm not sure if it would be a good fix, or maybe the problem is related to the node version. If the latest, maybe 1.7.2 should be restricted to higher versions of NodeJs

**Comment by nmccready** [comment]
Ugh,  yeah your right. I'll revert the es6 tomorrow. Unpublish 1.7.2 and
push 1.7.

Sent from my mobile device
======================
VR,

Nicholas McCready
twitter:nmccready
email:nmccready@gmail.com
github:nmccready

**Comment by nmccready** [comment]
Basically in a nut shell this not compatible with node 0.x

**Comment by acolchado** [comment]
@nmccready Thanks in advance for getting this resolved! Just noticed that a few of our builds started failing recently.

**Comment by fishgills** [comment]
We stumbled across this as well. All of our builds just started breaking. :(

**Comment by abey-alex** [comment]
+1

**Comment by abhiranjan** [comment]
+1 breaking our builds as well

**Comment by tsv2013** [comment]
+1

**Comment by mgriffel** [comment]
+1

**Comment by mgriffel** [comment]
+1

**Comment by mgriffel** [comment]
+1

**Comment by mgriffel** [comment]
+1

**Comment by mgriffel** [comment]
+1

**Comment by mgriffel** [comment]
+1

**Comment by nmccready** [comment]
Done https://github.com/floridoo/gulp-sourcemaps/releases/tag/v1.7.3

8ecaa7320d0c656514dfc07b15611d682f757818
39e1b3b1ffee13620e6d56fc4c673c04271406ec

Important notes:

debug-fabulous also had to be made node compat 0.X as well as lazy-debug

https://github.com/nmccready/debug-fabulous/commit/696f343617dce122ae03dc95e47050e48e87e3d4

**Comment by jreading** [comment]
Can you publish this?

**Comment by nmccready** [comment]
1.7.3 has been published

**Comment by nmccready** [comment]
If your using 2.X and you have es6 problems then your using the wrong version of node or you should be using 1.X of this project.
