### ISSUE TITLE
Error: Cannot find module './src/init'

### ISSUE THREAD

**Issue by mvattuone** [floridoo/gulp-sourcemaps#240]
Hey there, I recently ran into an issue while trying to build a site on jenkins, and it looks like the recent update to `gulp-sourcemaps` introduced an error:

`Error: Cannot find module './src/init'`

This appears to be happening in your `index.js` file where the `init` require happens.

Not exactly sure why since it looks like you are exporting the init method properly, and requiring it in `index.js` correctly, but I am likely going to pull this down and see if I can figure it out.

**Comment by joefeser** [comment]
See #238

**Comment by mvattuone** [comment]
Closing because there are two other issues and I am pretty sure the maintainer knows it is an issue. :)

**Comment by nmccready** [comment]
#238 orig

**Comment by nmccready** [comment]
@mvattuone thank you
