### ISSUE TITLE
src/ directory is excluded when npm install-ing

### ISSUE THREAD

**Issue by martinbean** [floridoo/gulp-sourcemaps#242]
When I run `npm install gulp-sourcemaps` it pulls in the package, but only **index.js**. The **src/** directory is missing and given that **index.js** essentially just `require`s `./src/init` and `./src/write`, breaks.

Why is the **src/** repository not included in `install`s? I can’t see an **.npmignore** file in the repository, so is the **src/** directory being excluded from `install`s by some other method? (Forgive me as I’m not a Node.js developer!)

**Comment by jordanmaslyn** [comment]
Ditto

**Comment by MrFusion42** [comment]
Please fix soon, it's breaking all sort of builds

**Comment by tdondich** [comment]
Ditto!

**Comment by martinbean** [comment]
Indeed. There’s a lot of angry Laravel developers who can’t `gulp` right now 😛

**Comment by djedi** [comment]
Ditto. Just downgraded to 2.0.0

**Comment by GasparMDQ** [comment]
Got the same error. I think may be related to the line 48 in package.json
`  "files": [
    "index.js"
  ],`

**Comment by peterkruty** [comment]
same here, cannot run react-native init as it's failing on the missing src/init

**Comment by ace4seven** [comment]
Same, please fix it.

**Comment by AndreyRavkov** [comment]
the same issue

**Comment by rmorrise** [comment]
Someone on [this thread](https://laracasts.com/discuss/channels/elixir/gulp-elixir-srcinit) mentioned that you can work around the issue by copying the file from the github repo. Where in my project am I supposed to place that file?

Thanks

**Comment by goodevilgenius** [comment]
Dupe: #238

**Comment by kayyyy** [comment]
Same here

**Comment by brysem** [comment]
I solved this problem by downloading the contents of this repository and replacing the gulp-sourcemaps folder with it in my node_modules folder. Adding "src" to the composer.json and reinstalling it with npm install didn't fix my problem.

**Comment by nmccready** [comment]
2.1.1 released and 1.8.1

**Comment by nmccready** [comment]
#238 orig

**Comment by nmccready** [comment]
My bad and to help your apps in the future `npm shrinkwrap` is your friend.
