### ISSUE TITLE
How to avert npm disaster via npm integration tests?

### ISSUE THREAD

**Issue by nmccready** [floridoo/gulp-sourcemaps#246]
Forking conversation from [here](https://github.com/floridoo/gulp-sourcemaps/issues/243#issuecomment-253660754)

Now here is a real question where I am looking for some constructive advice. I would have never pushed this problem if it would have been caught on travis or on local specs. So are there any mock npm publishing / integration specs that anyone already has to avoid this kind of disaster again?

@PWKad

**Comment by nmccready** [comment]
@PWKad
Hmm I guess you could link it in a script and install it or set up a free sinopia server (if there is > such a thing) on CI to test?

@nmccready
cool any examples or psuedo code to mock in a gist?

@PWKad
I would expect a shell script like this to work - 

```shell
$ cd {source folder}
$ npm link
$ cd ..
$ mkdir test
$ npm link gulp-sourcemaps
```

 I think if you run that on Travis and it fails the build would fail but I'd have to test that.

**Comment by aredridel** [comment]
One thing you can do is use `npm pack` to get a tarball and `npm install thattarball` to test it; though there was no error installing it, but requiring the installed module. It's not a complete solution, but parts that could be made into one.

You can even `npm publish` from a tarball, to break the steps up.

**Comment by nmccready** [comment]
Right but you can use libraries to untar it and the  inspect the contents. So thats a good plan.

**Comment by aredridel** [comment]
Yep! Lotta good options there -- even install in a temp dir, and require that.

**Comment by doowb** [comment]
I usually use [normalize-pkg](https://www.npmjs.com/package/normalize-pkg) from the command line and it'll usually catch files and folders missing from the `files` property.

[update](https://github.com/update/update) is a good tool to use also. If there isn't an updater available for this specifically, request one or create one locally to do what you need.

**Comment by moodysalem** [comment]
Is there any use case for npm to allow publishing modules that don't have exact dependency versions?

**Comment by nmccready** [comment]
It had the correct version but what would help is if npm publish failed if it ran the specs on npm during publish.

**Comment by aredridel** [comment]
@moodysalem Letting security updates in transitive dependencies happen is perhaps the most important. Library authors sometimes go AWOL (and should be able to! We gotta get out and do other things sometimes!)

**Comment by nmccready** [comment]
One problem with my precious thought though is the specs / tests are not usually pushed on npm. But I guess they could be temporarily to run. Upon passing it does the normal same old process.

**Comment by nmccready** [comment]
Actually, in this case you don't even need the specs. If npm publish would attempt to even load the main file it would have failed. So that step would help at the very least.

**Comment by aredridel** [comment]
There's a tension here, and I think mostly semver is the right bet. Mark breaking changes. If it screws up, patch the depending module, and you get a ticket to the bug tracker to yell if something broke that way. 

That said, we could really use some better tooling for overriding a transitive dependency sometimes. Lockfiles, etc, are a topic of conversation -- I think they're a great tool for an application, the root package that is being worked with, but tend to be a bad thing if they are used by library authors (they can't know the final use case!)

npm's shrinkwraps are currently, imo, kinda awkward. They're trending toward working as designed finally but there's some criticism of the design itself I think to make right now. npm@5 may have some shrinkwrap changes in it -- watch the npm client repo for progress and places to give your input if this matters to you!

At some point someone suggested a 'time travel registry' "install with what was published as of this time" and that could be a novel, different way to solve this kind of problem.

Definitely chime in with thoughts on this -- this is a known, difficult, and possible to improve situation that I think there are still more ways to keep the flexibility of unpinned versions without this breaking at times.

**Comment by nmccready** [comment]
Yeah shrinkwrap does only really help your root application. So great point there. 

As far as being responsive,  it would be nice to have more admins. Where they have both github and npm privileges.

**Comment by aredridel** [comment]
Putting the specs in a `prepublish` (soon to be `prepare` script) is a thing that may help this. There's the complication of only publishing a stripped build, and only dist files when there's a build system and source to source transforms. I've avoided that in my own packages so far, just for that reason -- I want the artifact generated to be complete into the future, even assuming the version control infrastructure has faded into long-dead obscurity. All these are pretty reasonable tradeoffs that I see arguments for on all sides.

**Comment by moodysalem** [comment]
semver is great as long as you follow it, but that requires developers to follow it... also you can easily break things when attempting to make a bug fix (which would result in a patch version)

The problem I had with using shrinkwrap is I had already deleted my node_modules folder so I couldn't generate a shrinkwrap file after I encountered the problem, and I wasn't interested in writing it by hand.

Maven doesn't have this problem IMO because the convention is to not use flexible versions for your dependencies. Also if you ran into this problem with a particular version, there are ways to exclude dependencies of dependencies as well as change transitive dependency versions from your project descriptor (similar to shrinkwrap)

I've run into this issue many times where a dependency gets updated and my application or build breaks. Shrinkwrapping throws out the loose dependency versions and seems to be the way to go for production builds so IMO it should just be the standard. If you want people to get an important  update, you should deprecate the older versions.

**Comment by aredridel** [comment]
Yeah. There's some tension there. I think I disagree, but not with your reasoning. 

I don't mind the semver negotiation -- we can pin deps by developers who don't semver (when we find out. Sigh. It is a community norm at least on the npm registry, by large, though) -- but it's just a ticket to file a bug, I think -- it won't prevent breaks, just communicate about which module has the fault it is when it breaks. We just need better tools to pick up and keep moving when it breaks.

_when_ it breaks. I _think_ we can have the best of both worlds.

**Comment by nmccready** [comment]
PR'ed #247 eyes 👀  please

**Comment by mllrjb** [comment]
@nmccready - since this is a general problem, I took a stab [at a small module](https://github.com/mllrjb/publish-sanity) to test the same thing (for my own team's sanity). Maybe it will be useful to you as well?

**Comment by nmccready** [comment]
@mllrjb cool, I would def add a ton of tests /specs . Once those get added maybe I'll include that.

**Comment by nmccready** [comment]
#247  was merged closing for now
