### ISSUE TITLE
combining sourcemaps over two gulp tasks yields hard to read maps

### ISSUE THREAD

**Issue by Nimelrian** [floridoo/gulp-sourcemaps#248]
gulp-sourcemaps version: 1.6.0 & 2.1.1

I have the following Gulp tasks:

```
gulp.task('compile-client-scripts', () => {
    return gulp.src(["!src/client/scripts/client.js", "src/client/scripts/**/*.js"])
        .pipe(sourcemaps.init())
        .pipe(babel({moduleIds: true}))
        .pipe(sourcemaps.write("."))
        .pipe(print())
        .pipe(gulp.dest("src/client/lib"));
});

gulp.task('concat-compiled-client-scripts', ['compile-client-scripts'], () => {
    return gulp.src("src/client/lib/**/*.js")
        .pipe(sourcemaps.init({loadMaps: true}))
        .pipe(concat("client.js"))
        .pipe(sourcemaps.write("."))
        .pipe(print())
        .pipe(gulp.dest("src/client/scripts"));
});
```

The final sourcemap map to the right places in code, but it generates a hard-to-read structure in the browser's (both FF and Chrome) devtools.

![image](https://cloud.githubusercontent.com/assets/8960836/19433909/02776758-9463-11e6-9a99-66ed8d8e1bce.png)

Do I have to specify another option to fix this or is what I want just not possible?

Edit: What I want to achieve as result:

The following Gulp task (Basically both above combined) generates the result below:

```
gulp.task('debug-client-scripts', () => {
    return gulp.src(["!src/client/scripts/client.js", "src/client/scripts/**/*.js"])
        .pipe(sourcemaps.init())
        .pipe(babel({moduleIds: true}))
        .pipe(concat("client.js"))
        .pipe(sourcemaps.write("."))
        .pipe(print())
        .pipe(gulp.dest("src/client/scripts"));
});
```

![image](https://cloud.githubusercontent.com/assets/8960836/19433948/3c12cb9c-9463-11e6-85ab-d1836c898d93.png)

**Comment by plamens** [comment]
I also observed that with gulp-sourcemaps 2.1.1. The problem is that paths in the properties of the generated sourceMap are relative to the base of the project, just like gulp-sourcemaps docs say.

For example:
if the file *./subdir/main.ts* is transpiled, the output source map will have the following property:
*"sources":["subdir/main.ts"]*

When the next build task inits a sourcemap with *loadMaps: true* and  loads this file, it will think that the *sources* property is relative to the sourceMap, so it will just append it to the path to the sourceMap. 
This happens at https://github.com/floridoo/gulp-sourcemaps/blob/master/src/init.js#L86
Thus, a part of the path will be duplicated and the sourceMap from the output of the second build task will have:
*"sources":["subdir/subdir/main.ts"]*

Here is an example project with 2 simple build tasks, one transpiles a typescript file and the other does a gulp-concat with just this file:
[example-project.zip](https://github.com/floridoo/gulp-sourcemaps/files/540989/example-project.zip)

**Comment by charpour** [comment]
I've also experienced the exact same problem... would appreciate some resolution.

**Comment by nmccready** [comment]
I believe these issues are related. #222  . Actually this issue seems like a dupe to me.

**Comment by plamens** [comment]
I don't think that's the same issue. This problem doesn't have anything to do with appended new lines. What is duplicated in this case is the path in the *sources* property of the sourceMap.
So, after a second build task that loads maps from the previous task, the resulting sourceMap has duplicate paths to the sources property. For Example:
"sources":["***_subdir/subdir_***/main.ts"]
instead of
"sources":["subdir/main.ts"]

**Comment by nmccready** [comment]
@Nimelrian nice example. If you would import your example into the `test\integration.js` we can try and make it pass the way you want. The example can be less complex as well if you desire.

Mean while I need to look into the write options like `sourceRoot`. Many examples of how it is supposed to work are defined [here](https://github.com/floridoo/gulp-sourcemaps/blob/master/test/write.js#L354-L510).

**Comment by nmccready** [comment]
@Nimelrian I worked on some more integration stuff here at
- https://github.com/floridoo/gulp-sourcemaps/blob/1.X/test/integration.js#L70-L124

To run it alone:
`npm run test:int`

It will output assets and sourcemaps to `./tmp`.  To serve it up on the browser run `npm run serve` and go to `http://localhost:8080/tmp/` . I will add another test for combining two sourcemap streams into one as you are.

**Comment by nmccready** [comment]
Here is another test combing files to (some pre-mapped/preExisting).

https://github.com/floridoo/gulp-sourcemaps/commit/43b20fbdf01f4718114081cf33681ccbe388154d

As you can see there was no need to combine streams via two tasks.

I will still try to do an example with what your producing as well.

**Comment by nmccready** [comment]
I added this test and went to it's results via `npm run serve`. Anyway I am not able to reproduce what you are having issues with. Also I do not think you need to be splitting out the task into two tasks using loadMap will work for everything as well.

- [test](https://github.com/floridoo/gulp-sourcemaps/blob/master/test/integration.js#L186-L209)

![screen shot 2016-11-21 at 9 10 38 pm](https://cloud.githubusercontent.com/assets/583593/20508412/75e979fa-b02f-11e6-87cf-26f97ef28a5f.png)

**Comment by plamens** [comment]
@nmccready , have you tried out the example project I uploaded with [my first comment on this issue](https://github.com/floridoo/gulp-sourcemaps/issues/248#issuecomment-255029669) ?
I can provide more detailed steps to reproduce, if that would help.

I just tested with 2.2.0 and this is still an issue.

**Comment by nmccready** [comment]
I didn't see the example-project.zip I'll pull it down and take  a look.

**Comment by nmccready** [comment]
@plamens @Nimelrian I think this has to deal with more of how your using gulp. gulp-sourcemaps and gulp are doing exact what you are telling them to do in you example.

The main issue is that when you run the task `compile-source-scripts` it keeps the folder integrity in the destination. Then you run gulp again on the source destination thus doubling the folder hierarchy. The simple solution is to flatten the files in the `compile-source-scripts` task.

[example.tar](https://dl.dropboxusercontent.com/u/10820326/example.tar)

Code:

```js
var gulp = require('gulp');
var flatten = require('gulp-flatten');
var typescript = require('gulp-typescript');
var concat = require('gulp-concat');
var sourcemaps = require('gulp-sourcemaps');
var destFileOptions = {mode: "755"};

function getTsCompilerOptions() {
   return {
      allowJs: true,
      noEmitOnError: true,
      target: "ES5"
   };
}

gulp.task('compileTypescript', function() {
   return gulp.src('views/**/*.ts')
         .pipe(sourcemaps.init())
         .pipe(typescript(getTsCompilerOptions()))
         .pipe(sourcemaps.write('.'))
         .pipe(flatten())// <------------ KEY to your problem
         .pipe(gulp.dest('transpiled-typescript', destFileOptions));
});

gulp.task('concatenateJavascript', ['compileTypescript'], function() {
   return gulp.src('transpiled-typescript/**/*.js')
         .pipe(sourcemaps.init({loadMaps: true}))
         .pipe(concat('index.js'))
         .pipe(sourcemaps.write('.'))
         .pipe(gulp.dest('dest', destFileOptions));
});

gulp.task('default', ['concatenateJavascript']);

```

**Comment by alexmironof** [comment]
Hi @nmccready! I can't use this workaround with `flatten()` :(

Is there another way to force ignore `sourceRoot` created in `compileTypescript` task or not appent duplicated path in the `concatenateJavascript` task?

**Comment by alexmironof** [comment]
@nmccready With this code at line everything works perfect for me.
[index.internals.js#L44](https://github.com/gulp-sourcemaps/gulp-sourcemaps/blob/b97fe7764c6fa443eddb64245306c8e1cf40f1a1/src/init/index.internals.js#L44)
`var absPath = options.loadMaps ? path.resolve(sources.path, path.basename(source)) : path.resolve(sources.path, source);`
