### ISSUE TITLE
Could not set source root to an empty string

### ISSUE THREAD

**Issue by lexon0011** [floridoo/gulp-sourcemaps#253]
I need to specify my mapped files in the "**sources**" property and set the "**sourceRoot**" to an empty string:
`{"version":3,"file":"components.js","sourceRoot":"","sources":"../../../../src/app/components/components.ts"],"names":[], ... }`

If I compile my files with the tsc with sourcemaps, it generates the sourcemaps as descripe above. But If I create the souremaps in my gulp task with gulp-sourcemaps, it generates the following:
`{"version":3,file":"components.js","sources":["components/components.ts"], ... }`

My configuration:
```
.pipe(plugins.sourcemaps.write('.', {
   includeContent: false, 
   sourceRoot: "",
   mapSources: function (file) {
      console.log(file);
   }
}))
```

With the `console.log(file)` I found out, that the path look different.
```
components\components.ts
..\src\app\components\help\help.component.ts
models\appState.ts
..\src\app\models\customEnums\cacheObjectType.ts
```

Have anyone an idea, why the path starts sometimes with "..\src\app\" and sometimes without this prefix?

**Comment by nmccready** [comment]
Please write an integration spec in [here](https://github.com/floridoo/gulp-sourcemaps/blob/1.X/test/integration.js) . You can add tsc or whatever deps into devDeopendencies to make it run.

Once you have that I can better take a look at what is failing in your scenario. Also don't forget to add your file (fixture) to .`/test/assets` .

**Comment by nmccready** [comment]
Closing until the test is produced
