### ISSUE TITLE
sourceRoot error

### ISSUE THREAD

**Issue by guohuihot** [floridoo/gulp-sourcemaps#254]
`sourceRoot: relativePath.split(path.sep).join('/')` => `..\..\..\..\site\HouseBundle\Resources\src` 
But in sourcemap file

`"sourceRoot":"../../../../../../../../../../../../site/HouseBundle/Resources/src"`

**Comment by nmccready** [comment]
Can you explain this a little more? Perhaps an additional spec would be clearer on your intent.

**Comment by nmccready** [comment]
Closing until a test is produced.

**Comment by guohuihot** [comment]
`sourceRoot: '..\..\..\..\site\HouseBundle\Resources\src'` => `..\..\..\..\site\HouseBundle\Resources\src` 
But in sourcemap file

`"sourceRoot":"../../../../../../../../../../../../site/HouseBundle/Resources/src"`
