### ISSUE TITLE
1.6.0 npm to github possible mismatch

### ISSUE THREAD

**Issue by bicubic** [floridoo/gulp-sourcemaps#256]
Howdy, 

I'm using version 1.6.0 from npm and my build script started ignoring `loadMaps: true` after doing a clean install despite the explicit older version being specified in package.json. I see that 1.6.0 from a two week old backup is different from the 1.6.0 fetched on the clean install. Possibly a regression has been introduced?

**Comment by nmccready** [comment]
Are you sure you were not targeting github vs. npm? NPM has not been rollback or touched on that version. I can see the code being mismatched if you were targeting master.

**Comment by bicubic** [comment]
I think so? My package.json contains `"gulp-sourcemaps": "^1.6.0"` and the change was brought on by blowing away node_modules followed by `npm install`

**Comment by nmccready** [comment]
I don't have time or enough information right now to track this down. Closing this for now until there is more of a lead to go on.
