### ISSUE TITLE
[npm] 1.9.1 is tagged as latest instead of 2.2.1

### ISSUE THREAD

**Issue by AgentME** [floridoo/gulp-sourcemaps#257]
When I ran `npm outdated` on a project of mine, I saw that gulp-sourcemaps version 1.9.1 is tagged as latest instead of version 2.2.1. Is this intentional?

**Comment by nmccready** [comment]
1.9.1 is the latest for the 1.X branch, and 2.2.1 is the latest for 2.X . They are the same code base with different dependencies. Where 2.X requires node >  4.X
