### ISSUE TITLE
npm update inconsistency

### ISSUE THREAD

**Issue by tgabi333** [floridoo/gulp-sourcemaps#259]
i got this when `npm outdated`

```
gulp-sourcemaps 
Current: 2.2.0
Wanted: 2.2.1
Latest: 1.9.1
```

**Comment by nmccready** [comment]
So 1.X and 2.X are essentially the same code except for dependencies an supported engines. All that happened here is 2.2.1 was pushed to npm prior to 1.9.1 . So it appears 1.9.1 is the latest. 2.2.1 is really the latest and if npm's versioning system works (wanting 2.X); you'r fine.

**Comment by tgabi333** [comment]
Thanks :)
