### ISSUE TITLE
Allow override of preExisting flag setting in init()

### ISSUE THREAD

**Issue by mikeyoon** [floridoo/gulp-sourcemaps#260]
When passing in an existing .js.map file using loadMaps, a preExisting flag in the `init()` function will get set. If this is set, then any modifications to the sourcemap filename will be ignored and the sourceMappingURL will point to whatever it was in the original JS file. When combined with a tool that renames the files, like gulp-cachebust, this will result in the .js file pointing to the wrong .map file.

Not sure what cases where maintaining the original sourcemap path is desirable even when the resulting sourcemap filename is different at the `write()` step, but if it is needed then I could make a PR to add an override for preExisting.

**Comment by nmccready** [comment]
The purpose of preExisting was to not modify the original source code of an existing sourcemap file. It used to append a new line regardless which caused undesired behaviors for some on their git versioning. Sounds like a bug where we need to still re-map the filename if changed but not add a new line.

Related issue: #222, and PR #255

**Comment by nmccready** [comment]
I need a better test case for handling your scenario so that #222 's test still pass but your's fails.

**Comment by nmccready** [comment]
I am going to revert the preExisting stuff, the only thing I am going to be keeping is removing the extra new line.

**Comment by nmccready** [comment]
Reverted:
- https://github.com/floridoo/gulp-sourcemaps/releases/tag/v1.9.2
- https://github.com/floridoo/gulp-sourcemaps/releases/tag/v2.2.2
