### ISSUE TITLE
Browserify + gulp-sourcemap = no luck (wrong paths and total mess)

### ISSUE THREAD

**Issue by OnkelTem** [floridoo/gulp-sourcemaps#261]
I tried really hard to come up with working configuration for getting sourcemaps done right in a simple project which uses Browserify but I gave up.

I've prepared a sample project which you can pull and try out:
https://github.com/OnkelTem/demo_sourcemaps_bug

Usage:
```
gulp serve
```

TL;DR: debugging doesn't work in IDE (WebStorm).

Please take a look into `docroot/js/main.js` and `docroot/js/main.js.map` - both are screwed up. Specifically:

- `docroot/js/main.js` for some odd reason contains the garbage from Browserify `//# sourceMappingURL=data:application/json;charset=....` instead of just `main.js.map`

- `docroot/js/main.js.map` has several issues:

1. `sources` array starting with not existing path `js/src/scripts/...` is wrong.
2. `file` property equals to `main.js` — i.e. w/o `js` prefix. I assume in this case there should be `sourceRoot` property set to '../'. 
3. there is still `preExisting` key with the original source data from Browserify. But I passed `includeContent: false` to the `write()` method, then shouldn't it be removed?

Workarounds. I found none, except of patching.

1) apply this patch

```
diff --git a/src/init.js b/src/init.js
index c1c405a..d285b38 100644
--- a/src/init.js
+++ b/src/init.js
@@ -84,7 +84,7 @@ function init(options) {
             sourceMap.sourcesContent[i] = sourceMap.sourcesContent[i] || null;
             return;
           }
-          var absPath = path.resolve(sourcePath, source);
+          var absPath = path.resolve(source);
           sourceMap.sources[i] = unixStylePath(path.relative(file.base, absPath));
 
           if (!sourceMap.sourcesContent[i]) {
@@ -200,8 +200,6 @@ function init(options) {
         sourcesContent: [fileContent]
       };
     }
-    else if(preExisting !== null && typeof preExisting !== 'undefined')
-      sourceMap.preExisting = preExisting
 
     sourceMap.file = unixStylePath(file.relative);
     file.sourceMap = sourceMap;
```

2) Call the `.write()` with `sourceRoot` set to the current directory value (uncomment the 1st variant in the `gulpfile.js`):

```
.pipe(sourcemaps.write('./', { includeContent: false, sourceRoot: './' }))
```

Now it starts working in WebStorm.

**Comment by nmccready** [comment]
I am swamped right now. If someone wants to make a PR and attempt to fix things; please feel free.

**Comment by OnkelTem** [comment]
I'm pretty sure the patch is dirty and would fail in other cases. So I don't feel like it's a candidate for a PR.

**Comment by nmccready** [comment]
@OnkelTem I removed the preEixsting stuff and unpublished 1.9.1 and 2.2.1 try 2.2.2 and 1.9.2
