### ISSUE TITLE
Incorrect relative paths in inline sourcemaps 

### ISSUE THREAD

**Issue by timfish** [floridoo/gulp-sourcemaps#262]
I have the following directory structure with `src` as the source directory and `dist` as the destination. 
```
+-- src
+-- www
    +-- dist
```
I'm generating inline sourcemaps with the following basic code:
```
.pipe(sourcemaps.init())
.pipe(typescriptProject())
.pipe(sourcemaps.write())
```

The "sources" path in the inline sourcemaps are relative so using `gulp-typescript` and `gulp-sourcemaps` the source file `./src/app.ts` ends up in `./www/dist/app.js` and the inline sourcemap "sources" path (in the base64 data) says `../../src/app.ts`. 

The file `./src/some/other/path/file.ts` ends up in `./www/dist/some/other/path/file.js` with a sourcemap "sources" path of `../../src/some/other/path/file.ts` whereas it should be `../../../../../src/some/other/path/file.ts`.

This means in the Chrome debugger, the sourcemaps aren't all displayed in the `./src/` directory. Instead they're scattered throughout the directory structure. 

The typescript compiler writes the sourcemaps with the correct relative paths.

If I pass the following `mapSources` function to `write`, the "sources" paths in the sourcemaps are correct, but `gulp-sourcemaps` then can't find the source file to inline the source code.
```
    mapSources: function (sourcePath) {
        return '../../../' + sourcePath;
     }
```

**Comment by timfish** [comment]
is this a duplicate of #163?

**Comment by nmccready** [comment]
They are probably related but if you could produce your example in the integration specs of this repo. This would make it a whole lot easier to understand your issue. For needed dependencies add them to `devDependencies`.

**Comment by nmccready** [comment]
Add your problem here https://github.com/floridoo/gulp-sourcemaps/blob/master/test/integration.js#L25-L47 . Then I can clearly see what is wrong. Closing until this done.
