### ISSUE TITLE
Multiple loads of the same bundled file

### ISSUE THREAD

**Issue by milanstamenkovic** [floridoo/gulp-sourcemaps#263]
Hi, I have the following gulp task:

```
gulp.task('default', () => {
  return gulp.src(['./test.js'])
      .pipe(sourcemaps.init())      
      .pipe(concat("bundle.js"))
      .pipe(sourcemaps.write('./'))
      .pipe(gulp.dest("./"));
});

```
and the following structure:
![image](https://cloud.githubusercontent.com/assets/9901106/21501339/54fd930a-cc47-11e6-912d-48f84cac55c2.png)

And the following situation: 
Index.html includes script bundle.js and has 2 frames, bundle.js is included as well as in frame1.html and frame2.html. 
You can see in the picture above that there is no source maps for bundle.js in frame1 and frame2, the problem is when debugging in Chromes dev tool, debugger breaks in bundle.js for frame1.html and frame2.html, for index.html it breaks in source map test.js.. 
test.js looks like:
```
(function(){
    var x = 10;
    console.log(x);
})();

```
I am not sure is this is a bug within dev tool or within gulp-sourcemaps plugin.

**Comment by nmccready** [comment]
Your gulp task looks correct, but there are too many unknowns to how your project is setup. Please reproduce your issue in (integration.js)(./test/integration.js)

**Comment by milanstamenkovic** [comment]
I have problem running that test, but project setup is simple. I have one html document which includes bundle.js (obtained with gulp) and in the body one iframe (src property is another html document which also includes bundle.js and have nothing more). I made this project just for testing purpose, to simplified situation and see if bug exists in that case. 

index.html: 
<html>
    <head>
        <script src='bundle.js'></script>
    </head>
    <body>
        <iframe src='frame1.html'></iframe>
    </body>
</html>

frame1.html:
<html>
    <head>
        <script src='bundle.js'></script>
    </head>
    <body>
    </body>
</html>

that's all, i have tried to upload but error with supported type appeared.
Thanks

**Comment by nmccready** [comment]
Closing until an actual full example is provided. Make a new repo or add a test to this project.

**Comment by milanstamenkovic** [comment]
Link to the repo:
https://github.com/milanstamenkovic/gulp_sourcemaps_test

**Comment by phated** [comment]
This is likely a chrome debugger problem.  Closing.
