### ISSUE TITLE
How do I get the absolute path (from project root) of the source or sourcemap file ?

### ISSUE THREAD

**Issue by dorongutman** [floridoo/gulp-sourcemaps#264]
I need to use a full path to the sourcemap file due to some logic (using private domains that are resolved only in-house but not outside of our office).
I want to keep the same path as the source file, but if I use the prefix option or a function to the write logic, it writes the sourcemap file at the root of my internal domain and not at the same folder as the source file.
My gulp process generates a few js and sourcemap files, in various directories.

**Comment by nmccready** [comment]
To set you sourcemaps to point to an absolute path you can do something like 
`.pipe(sourcemaps.write('.',{sourceRoot:'/Users/someuser/test/assets'}))`

To get the path you use the File provided in the stream via Vinyl.

https://github.com/gulpjs/vinyl#filepath

https://github.com/floridoo/gulp-sourcemaps/blob/master/src/init/index.js#L52
