### ISSUE TITLE
NPM registry doesn't show latest release

### ISSUE THREAD

**Issue by valera-rozuvan** [floridoo/gulp-sourcemaps#266]
If you check https://www.npmjs.com/package/gulp-sourcemaps , you will see that it swhows **v1.9.1** as the latest release of **gulp-sourcemaps**. However, on the page https://github.com/floridoo/gulp-sourcemaps/releases you can see that there is a **v2.2.1** release. Which one is the latest?

**Comment by nmccready** [comment]
Dupe #259 #257 , please search old issues
