### ISSUE TITLE
Version 1.9.1 not available on npm anymore?

### ISSUE THREAD

**Issue by vhf** [floridoo/gulp-sourcemaps#268]
Our travis builds started failing because npm cannot install `gulp-sourcemaps@1.9.1` anymore since a couple of hours ago.

Since `1.9.1` was published more than 24 hours ago, unpublishing it from npm would have required an action taken by npm. I'm not sure 1.9.1 was really unpublished but it's impossible for me or for travis to install it:

```
$ npm show gulp-sourcemaps versions | grep 1.9
  '1.9.0',
  '1.9.2',
```

Do you happen to know why this happened?

**Comment by nmccready** [comment]
1.9.1 has been unpublished use 1.9.2

**Comment by nmccready** [comment]
I'll try and republish it, it's a buggy release. But I should have left it on npm.

**Comment by vhf** [comment]
👍  Thanks!

We'll upgrade to 1.9.2 when we get the chance to review the changelog.

**Comment by nmccready** [comment]
I'll have to contact an admin at npm directly. I cant repub 1.9.1 or 2.2.1 see http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f

**Comment by nmccready** [comment]
I contacted them and I am waiting.

**Comment by mattdsteele** [comment]
I'm curious, how was this unpublished? Based on [npm's stated policy](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy) I didn't think unpublishing a module after 24 hours was possible.

**Comment by nmccready** [comment]
That is a question for npm.

**Comment by seldo** [comment]
We are looking into how this was possible. We have a support ticket from @nmccready and will reply there.

**Comment by nmccready** [comment]
Npm put it back
