### ISSUE TITLE
No mappings to SASS files that are imported

### ISSUE THREAD

**Issue by clayton93** [floridoo/gulp-sourcemaps#271]
Hi, I have tried to solve my problem by looking through the current/ old issues but can not find anything that will help.

I am trying to create a source map whilst also using gulp-sass and gulp-autoprefixer.

I have the following file structure:
```
- css
    - compiled/ sassified css and maps go here
- sass
    - theme.scss
    - theme
        - home.scss
        - mixins.scss
        - ...
```

In `theme.scss` I have imports that call each of the files in the `theme` folder adjacent to it. 

When I try to create a source map on this, all of the mappings only refer to the `theme.scss` file and not any of the imported files the styles come from.

My gulp task is as follows:
```javascript
gulp.task('sass:compile', ['lint:sass'], function () {
	return gulp.src('./sass/*.scss')
	.pipe(plumber({
	    errorHandler: onError
	}))
	.pipe(sourcemaps.init({loadMaps: true}))
	.pipe(sass({
	    style: 'compact'
	}))
	.pipe(autoprefixer())
	.pipe(sourcemaps.write('.'))
	.pipe(gulp.dest('./css'));
});
```

The source map outputs the following:
`{"version":3,"file":"theme.css","sources":["/sass/theme.css","/sass/theme.css","/sass/theme.css"]...`

I am really not sure what else to try. I have tried lots of fixes from the various issue I have found but none that can solve my problem. I'm sorry if I am being dull.

**Comment by MannyC** [comment]
This is a bug, fixed in v1.10.1 and v2.3.1

**Comment by nmccready** [comment]
Thanks @MannyC , he is right

**Comment by clayton93** [comment]
Sorry I didn't see that new update as only installed it yesterday. Thanks a lot @MannyC @nmccready!

**Comment by nmccready** [comment]
Bug fix [here](https://github.com/floridoo/gulp-sourcemaps/commit/0afd11c7bf98d615ec795c36c671f0c2bee86dd7)

Related #270
