### ISSUE TITLE
Double path for map files

### ISSUE THREAD

**Issue by yesman85** [floridoo/gulp-sourcemaps#272]
I use VS with gulp and I have my directory structure like this:

/App
/App/App.ts
/App/Directives/hasRole.ts

Using this gulp to generate:
```
gulp.task('typescript',
    function()
    {
        var tsProject = ts.createProject('./app/tsconfig.json',
            {
                typescript: require('typescript')
            });

        var tsResult = tsProject.src()
            .pipe(sourcemaps.init())
            .pipe(tsProject())
            .on('error',
                function(error)
                {
                    gutil.log('Typescript compilation exited with errors');
                    process.exit(1);
                });

        return tsResult.js.pipe(sourcemaps.write('.',
                {
                    includeContent: false,
                    sourceRoot: '/App'
                }))
            .pipe(gulp.dest('./App'));
    });
```
Now I was using 1.9.1 and it generates a source file like this:

```
{"version":3,"sources":["Directives/hasRole.ts"],"names":[],"mappings":"...","file":"hasRole.js","sourceRoot":"/App"}
```

Which is fine, but in the newer version it generates it like this:

```
{"version":3,"sources":["/App/directives/Directives/hasRole.ts"],"names":[],"mappings":"...","file":"hasRole.js","sourceRoot":"/App"}
```

I looked through the source but I'm confused why Directives is placed twice in there?

**Comment by twiggy** [comment]
I think I can confirm this. 

Pre 1.10 sources came out as "views/common/xxxx.js" now they are /resources/js/views/common/xxxx.js

We are just pegging to the old version for now.

I don't have a few moments to create a test for this today, but I should be able to at some point in the near future.

I don't think we are using sourceRoot at all either.

Thanks!

**Comment by yesman85** [comment]
I changed the sourceRoot to other values or even removed it but it's not related to the sources element.

**Comment by nmccready** [comment]
It is happening due to this code.

https://github.com/floridoo/gulp-sourcemaps/blob/master/src/write/index.internals.js#L47-L53

The reasoning was to get rid of filePaths with ../../../whatever where it was outside of sourceRoot. I could add an option just to due the legacy if returning filePath.

You can just submit the mapSources: function as an option  and make it behave how you want.

**Comment by weinand** [comment]
Yes, starting with gulp-sourcemap 1.10 entries in the `sources` array of a source map start with a leading '/' which makes them absolute. This prevents tools like VS Code to combine the paths with the value of `sourceRoot` and results in problems locating the source.

**Comment by nmccready** [comment]
Ok, I will make the change optional with a flag for mapSourcesAbsolute and make the default what it was. I made the change as it seemed worthless without it as I could not get the desired structure I wanted to stay within sourceRoot.

**Comment by weinand** [comment]
@nmccready great, thanks.

**Comment by yesman85** [comment]
@nmccready but does this address the actual bug where the paths get duplicated in the source file? I'm not worried about having an absolute path in the sources array.

**Comment by nmccready** [comment]
@yesman85 what version are you running. The dupes should be gone in 1.10.1 and 2.3.1 .

**Comment by nmccready** [comment]
@yesman85 if they are not gone, make an integration test and PR it! All you need to do is copy and modify these lines.

https://github.com/floridoo/gulp-sourcemaps/blob/master/test/integration.js#L234-L260

Any gulp plugin dependencies should be installed to devDependencies.

**Comment by nmccready** [comment]
2.4.0 & 1.11.0 released

https://github.com/floridoo/gulp-sourcemaps/commit/fb4027a496898b8b7992ea5af9b3d707f1d82d38#diff-1f2c3e6bbae8865c04ea81906e82bd74R52

**Comment by phated** [comment]
Assuming this is fixed/complete.
