### ISSUE TITLE
sass imports

### ISSUE THREAD

**Issue by dazdylz** [floridoo/gulp-sourcemaps#275]
Hi,

This is my code:
`gulp.task('compileSass', () => {
    return gulp.src('src/scss/main.scss')
        .pipe(sourcemaps.init())
        .pipe(sass().on('error', sass.logError))
        .pipe(sourcemaps.write())
        .pipe(concat('bundle.css'))
        .pipe(gulp.dest('dist/'));
});`

And my main.scss:
`@import "a";
@import "b";`

The source maps works perfectly now. 

I want to add a vendor file (vendor/bootstrap/style.css):
`@import "vendor/bootstrap/style.css";
@import "a";
@import "b";`

but now the sourcemaps are not working correct. the contents from _a.scss and _b,scss are displayed as they are both in _b.scss and the vendor/bootstrap/style.css points to the main.scss file.

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
