### ISSUE TITLE
gulp-requirejs-optimize AND gulp-babel

### ISSUE THREAD

**Issue by thany** [floridoo/gulp-sourcemaps#278]
Both of these modules are reported on the wiki as supporting gulp-sourcemaps, but I've found Babel doesn't work well:

https://github.com/babel/gulp-babel/issues/108

TLDR: when I add Babel in the mix, sourcemaps are only generated for the entry point. 

This *might* be a gulp-sourcemaps bug, which is why I though I'd post it here. Sorry if it turns out not to be.

**Comment by nmccready** [comment]
Can you produce a small example pipeline that I can play with? Feel free to use the integration.js test file.

**Comment by thany** [comment]
I made a skeleton out of my existing project (which is huge, so I won't bother you with that 😃) and here it is:
[qsdashboard-test.zip](https://github.com/floridoo/gulp-sourcemaps/files/799763/qsdashboard-test.zip)
If you run the following...
```
bower install
npm i
gulp
```
...the project should build.
Then:
```
source-map-explorer build/js/main.js
```
Gives the error mentioned.

Thanks in advance 😀

**Comment by thany** [comment]
So, have you been able to play with this? I'm not in a hurry or anything, so do take your time. I'm just curious how it's going :)

**Comment by nmccready** [comment]
@thany sorry about this; I just started a new position and I have been face down in ramping up with zero time for OS projects. I am trying to get more devs on this project to contribute. However, I am in knee deep in the middle in organizing that.

**Comment by phated** [comment]
The problem is with one of those 2 plugins.  I'm fairly certain `gulp-requirejs-optimize` should be on the blacklist because it is using requirejs to traverse the filesystem but I'm don't have the time to dig into that right now.  Either way, this isn't a gulp-sourcemaps problem.
