### ISSUE TITLE
Difference between destPath argument and option

### ISSUE THREAD

**Issue by phated** [floridoo/gulp-sourcemaps#280]
I can't seem to figure out the difference between the first argument (`destPath`) and the option of the same name.  Could you explain them a bit more?

**Comment by nmccready** [comment]
I totally agree this is confusing and was already this way prior to contributing. If I get some time I'll try and figure it out.

**Comment by phated** [comment]
@nmccready thanks!  I've been looking at the 1 test regarding `destPath` option, some issues and the source this morning.  It feels like the `destPath` option is really something like `sourceDirectory` since it is used to resolve the directory portion of the `file.sourceMap.file` property.  Thoughts?

**Comment by nmccready** [comment]
> It feels like the destPath option is really something like sourceDirectory since it is used to resolve the directory portion of the file.sourceMap.file property

For clarity lets define `destPath` as `sourceDirectory` in this conversation.

I agree; but there is some weird issues where if you define `sourceDirectory` and `options.destPath` where `sourceDirectory` is not obeyed. There were no comments here and I was really left scratching my head as to what was going on. Therefore to get anything working for myself in a different `sourceDirectory` I had just avoided `options.destPath` at all costs.

So clearing up `options.destPath`'s purpose would go a long way. There seems to be a few tests for these cases; but I am not sure if there are enough of them. Especially to dig into some edge cases.

Here are some of them https://github.com/floridoo/gulp-sourcemaps/blob/master/test/write.js#L199-L296 .

**Comment by phated** [comment]
I was actually defining them the opposite way.  `destPath` feels like the destination path for the sourceMaps (when output by `gulp.dest`) while `options.destPath` feels like it should be defined as `options.sourceDirectory` since it is defining where the sourceMap's File is located.

Some of those tests seem like they aren't really testing the option and it was just tacked on (maybe copy-paste?).  I've been looking at https://github.com/floridoo/gulp-sourcemaps/blob/master/test/write.js#L394-L421 and the option seems to be ignored completely, which is weird.

**Comment by phated** [comment]
I'm actually considering removing the option (and all logic) for `vinyl-sourcemap` and seeing if anyone actually uses it.  It might help us understand the actual use cases for it and come up with better naming/logic surrounding it.

**Comment by phated** [comment]
Found the commit but can't understand the description: https://github.com/floridoo/gulp-sourcemaps/commit/dcc5a8ff2e83024ac76e91348800d973b1d9d464

**Comment by phated** [comment]
Looking into the spec, the `sourceMap.file` property is defined as "An optional name of the generated code that this source map is associated with.", so it doesn't actually point to a file and is just a reference name.  Given that, it's probably fine to toss out the `options.destPath` and replace with `options.file` to be resolved against each sourceMap and assigned to `sourceMap.file`.

The only thing lost by these changes would be automatic `sourceMap.sourceRoot` resolution but I suppose that it could be resolved by using `path.resolve` with the result of `options.file` or something similar.

**Comment by phated** [comment]
I think we dived sufficiently deep into this.  I'm going to close it to keep the tracker clean
