### ISSUE TITLE
loadMaps and rewrite them inline in file

### ISSUE THREAD

**Issue by Adavo** [floridoo/gulp-sourcemaps#281]
Hi,

I use VS2015 which compile my typescript and concat it into one file (mainTs.js) and generate a source map for it (mainTs.js.map). 

Unfortunately, when I deploy my app with Cordova on android phone, is impossible to get the source map (see https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/c54b6CxWhwU for more details). It seems that the solution is to generate the sourcemap inline (so at the end of the js file).

As I already have a map file, I want to:
- load this map file
- rewrite his content at the end of my js file

According to the documentation, here is what I did:

    gulp.src('./core/mainTs.js')
          .pipe(sourcemaps.init({ loadMaps: true }))
          .pipe(sourcemaps.write())
          .pipe(gulp.dest('./core'))

And the result is to add this line at the end of my mainTs.js:
//# sourceMappingURL=mainTs.js.map

but still not working (exactly same situation as the user in the previous shared google group link).

My question is:
- Is it possible to do what I want to do and how can I proceed if it's possible?
- If it's not possible, do you plan to allow this kind of thing in a near future?

Thanks for your help

**Comment by phated** [comment]
It's possible your sourcemap is too big and you need `largeFile: true` in your `init` options, as documented at https://github.com/floridoo/gulp-sourcemaps#handle-large-files
