### ISSUE TITLE
Help sass doesn't compile wi

### ISSUE THREAD

**Issue by inesantos29** [floridoo/gulp-sourcemaps#282]
Compile sass width gulp 
I want sass compile automatically when I change scss and notify a message

Folders:
-css - libs - bootstrap.min.css
                   - fonts
         -style
-scss -libs
          - project
          -style
-js
- node_modules
package.jason
index.html
gulpfile.js

gulpfile.js 

'use strict';

var gulp = require('gulp');
var sass = require('gulp-sass');
var notify = require('gulp-notify');
var sourcemaps = require('gulp-sourcemaps');
var autoprefixer = require('autoprefixer');

gulp.task('styles', function() {
    return gulp.src('scss/**/*.scss')
        .pipe(sass().on('error', sass.logError))
        .pipe(sourcemaps.init())
        .pipe(sass({ style: 'expanded' }))
        .pipe(autoprefixer('last 2 version'))
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('css'))
        .pipe(rename({suffix: '.min'}))
        .pipe(minifycss())
        .pipe(gulp.dest('css'))
        .pipe(connect.reload())
        .pipe(notify({ message: 'Styles task complete' }));
});

//Watch task
gulp.task('default',function() {
    gulp.watch('sass/**/*.scss',['styles']);
});

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
