### ISSUE TITLE
Option identityMap doesn't work for Sass-files.

### ISSUE THREAD

**Issue by simonboyko** [floridoo/gulp-sourcemaps#283]
Option identityMap doesn't work for *.scss files. I use in the project gulp with gulp-sourcemaps, and gulp-sass, gulp-autoprefixer. I compile but in a browser I see a linenumber of selector in root of the sourcefile, but I need to see the linenumber of the nested selectors.
My gulp task:
> gulp.task('sass', function () {
        gulp.src('sass/**/*.scss')
        .pipe(sourcemaps.init({loadMaps: true, identityMap: true}))
        .pipe(sass()).on('error', sass.logError)
        .pipe(autoprefixer({
            browsers: ['last 10 versions'],
            cascade: false
        }))
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('css/'));
    });

Versions of the packeges from package.json:
> "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.1",
    "gulp-sass": "^3.1.0",
    "gulp-sourcemaps": "^2.4.1"

May be I do something wrong? # #

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
