### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by SystemParadox** [floridoo/gulp-sourcemaps#73]
When trying to run browserify+uglify using gulp-sourcemaps, I get the following error:

```
node_modules/gulp-sourcemaps/node_modules/convert-source-map/index.js:109
  var m = content.match(commentRx);
                  ^
RangeError: Maximum call stack size exceeded
```

The gulp task looks a bit like this:
```
var browserify = require('browserify');
var source = require('vinyl-source-stream');
var buffer = require('vinyl-buffer');
var uglify = require('gulp-uglify');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('bundle', function () {
    var bundle = browserify({
        debug: true,
    });
    bundle.bundle()
    .on('error', gutil.log.bind(gutil, 'Browserify Error'))
    .pipe(source(getBundleName('client')))
    .pipe(buffer())
    .pipe(sourcemaps.init({loadMaps: true}))
    .pipe(uglify())
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest('./build'));
});
```

This happens with gulp-sourcemaps 1.2.8. Downgrading to 1.1.0 fixes it. With 1.2.8, this issue occurs even if the uglify line is commented out.

The same issue also occurs unless I specifically use gulp-uglify 0.3.1. Any later version also breaks it.

Possibly this is something to do with very large sourcemaps.

Any help would be much appreciated.

Thanks.

**Comment by AgentME** [comment]
This bug has been blocking me from moving a large project to browserify. Here's an example repo that shows the issue: https://github.com/AgentME/sm-test

**Comment by andrenarchy** [comment]
I'm encountering the same issue. @floridoo any ideas yet?

**Comment by wwilsman** [comment]
+1

**Comment by mtr** [comment]
+1. I'm also experiencing this issue.

**Comment by qmmr** [comment]
+1 Exactly the same issue.

**Comment by wavded** [comment]
Perhaps related: https://github.com/thlorenz/convert-source-map/pull/10
I notice this issue as well, are you people using io.js when they see the issue?

**Comment by jmullo** [comment]
The same issue with a big enough project. Doesn't really have to be a monster project...

**Comment by fetis** [comment]
I have a same issuse. 
As temp workaround I can say that removal of `loadMaps: true` helps me

**Comment by AgentME** [comment]
@wavded I'm not currently using iojs. As far as I know, the example I linked to earlier (https://github.com/AgentME/sm-test) always fails under node.

**Comment by wavded** [comment]
@AgentME hmm random.  when i switched to node from iojs yesterday it started working but i'm back on iojs today its working again.

**Comment by AgentME** [comment]
gulp-sourcemaps 1.4.0 fixes my original issue and my example test case (https://github.com/AgentME/sm-test).

**Comment by floridoo** [comment]
Good to hear @AgentME!

**Comment by andrenarchy** [comment]
Fixed here too, thx!

**Comment by wavded** [comment]
Fixed it for me as well.

**Comment by nschloe** [comment]
I just bumped into this with gulps-sourcemaps 1.5.2, see [travis](https://travis-ci.org/paperhive/paperhive-frontend/builds/63044465#L373).

**Comment by wavded** [comment]
I noticed the issue returned for me as well.

**Comment by andrenarchy** [comment]
Same here. *[Grim memories and bad flashbacks](https://www.youtube.com/watch?v=AQMNSIKThVo)* :grinning:

**Comment by Dynom** [comment]
+1 with the returned issue.

**Comment by craigdallimore** [comment]
I am encountering this on `node 4.2.2 LTS`. I've tried `gulp-sourcemaps@1.4` and `@1.6`.

**Comment by nmccready** [comment]
For me this only happens when I have two styles compiling the same time. Example:

```
//where set 1 and 2 both doe css , less, and stylus sourcemapping
gulp.task('manyStyles', gulp.parallel('styleSet1', 'styleSet2') //explodes
gulp.task('manyStyles', gulp.series('styleSet1', 'styleSet2') //is fine
```

**Comment by nmccready** [comment]
In the same boat as @craigdallimore with only the above workaround that gets around it.

**Comment by craigdallimore** [comment]
@nmccready many thanks.

For those on `gulp@3.x`, `run-sequence` appears to solve this too, which I _think_ is much the same thing and `gulp.series`.

**Comment by ceremcem** [comment]
```
node_modules/gulp-sourcemaps/node_modules/convert-source-map/index.js:122
  var m = content.match(commentRx);
                  ^

RangeError: Maximum call stack size exceeded
```

Problem carries on with latest git repository (by now).

**Comment by nmccready** [comment]
Use the largeFiles option.
