### ISSUE TITLE
Problem working with gulp-less

### ISSUE THREAD

**Issue by mudetroit** [floridoo/gulp-sourcemaps#78]
I am getting an error out of gulp-less, but as you can see I am not receiving any details from it, making it difficult for me to pinpoint what the issue is..

When I remove sourcemaps from the equation the error goes away. I am not certain if it is being generated by gulp-less or gulp-sourcemaps, but something in the interaction of the two is causing an odd error. I will cross post this on gulp-sourcemaps as well.
```
[11:57:04] Starting 'styles'...
[11:57:06] Plumber found unhandled error:
 Error in plugin 'gulp-less'
Message:
    First argument needs to be a number, array or string. in file undefined line no. undefined
Details:
    lineNumber: undefined
    fileName: undefined
[11:57:07] Finished 'styles' after 3.02 s
[11:57:07] Starting 'watch'...
[11:57:07] Finished 'watch' after 155 ms
[11:57:07] Starting 'clientBuild'...
[11:57:07] Finished 'clientBuild' after 5.1 μs
```

Here is the styles task that runs gul less, it is coffeescript, but should be legible.
```
gulp = require 'gulp'
{less, sourcemaps, plumber} = require('gulp-load-plugins')()

gulp.task 'styles', ->
	gulp.src(['./public/include/less/**/*.less', '!./**/_*.less'])
	.pipe plumber()
	.pipe sourcemaps.init()
	.pipe less({verbose: true})
	.pipe sourcemaps.write()
	.pipe gulp.dest('./public/include/css')
```
reference plus3network/gulp-less#121

**Comment by heikki** [comment]
@mudetroit Can you confirm this works & close the issue?

**Comment by floridoo** [comment]
@mudetroit Can I close this?

**Comment by mudetroit** [comment]
I was able to get it to work... I was never able to get the error to output properly. I had to slowly include files to track it down
