### ISSUE TITLE
Unable to debug source when using .map file

### ISSUE THREAD

**Issue by corydeppen** [floridoo/gulp-sourcemaps#80]
I have a small script that includes an embedded source map and has been minified using gulp-uglify.

```
function bundleApp(module) {
    var bundler = browserify({
        debug: true,
        entries: module.path,
        paths: bundlePaths
    });

    var bundle = function () {
        return bundler
            .bundle()
            .pipe(source(module.name + '.min.js'))
            .pipe(buffer())
            .pipe(sourcemaps.init({ loadMaps: true }))
            .pipe(uglify())
            .pipe(sourcemaps.write())
            .pipe(gulp.dest('Scripts'));
    };

    return bundle();
}
```

This allows me to break into the script as expected. When I write the map to a file using `sourcemaps.write('./')`, I break into the minified script and see the following:

```
// Please wait a bit.
// Compiled script is not shown while source map is being loaded!
```

I'm not sure if this could be related to the loading sequence and is normal, or if there's something I'm not aware of that could be causing this issue.

(browserify 8.0.1, gulp-sourcemaps 1.3.0, gulp-uglify 1.1.0)

**Comment by heikki** [comment]
Trailing slash is not needed: `sourcemaps.write('.')`. Is there separate `.map` file next to your javascript file?

**Comment by corydeppen** [comment]
The corresponding `.map` file is requested, but there are many other requests between it and the minified script. If this is a race condition, I'd think this would be a common issue.

**Comment by heikki** [comment]
If the map file is ok then this can't be gulp-sourcemaps issue.

**Comment by nickmeldrum** [comment]
Got a similar issue using gulp and browserify but turned out to be a chrome issue and it's fixed in canary: https://code.google.com/p/chromium/issues/detail?id=424191
