### ISSUE TITLE
On generating correct sourceRoot with an extra argument

### ISSUE THREAD

**Issue by jiyinyiyong** [floridoo/gulp-sourcemaps#81]
I just finished implementing my plugin with this plugin. It made me a bit confused that in my case I have to use a argument to specify the compiled path(relative to `file.base`) so I can generate to correct `sourceRoot` and `sources` with Mozilla's `source-map` module. Like this:

```
build/
  a.js
  b/c.js
source/
  a.cirru
  b/c.cirru
```

```coffee
gulp
  .src 'source/**/*.cirru', base: 'source/'
  .pipe sourcemaps.init(debug: yes)
  .pipe script(dest: '../build/') # from `source/` to `build/`
  .pipe rename(extname: '.js')
  .pipe sourcemaps.write('./')
  .pipe gulp.dest('build/')
```

And as I went through some other plugins implemented `gulp-sourcemaps`, I found none of them are using such an arguement? Does it mean that they don'y care about that `sourceRoot` and `sources`?

**Comment by floridoo** [comment]
The convention is to have all paths in `sources` to be relative to `base` and specifying the `sourceRoot` just at the end in `sourcemaps.write()`.
In the future, source map support will be included in the gulp core, which allows to set the `sourceRoot` automatically (in `gulp.dest`).

**Comment by jiyinyiyong** [comment]
That's good news, looking forward to it.
