### ISSUE TITLE
" First argument needs to be a number, array or string" error on empty input

### ISSUE THREAD

**Issue by Pomax** [floridoo/gulp-sourcemaps#82]
The following code will fail because sourcemaps gets incredibly confused what to do if an empty file is encountered:
```
gulp.task('less-app', function() {
  var less = require('gulp-less');
  var plumber = require('gulp-plumber');
  var sourcemaps = require('gulp-sourcemaps');

  return gulp.src('./less/*.less')
      .pipe(plumber())
      .pipe(sourcemaps.init())
      .pipe(less())
      .pipe(sourcemaps.write())
      .pipe(gulp.dest(cwd + '/public/stylesheets'));
});
```

If I run this on a dir with a file `test.less` that has no content, sourcemaps errors out:

```
[15:25:55] Starting 'less-app'...
[15:25:55] Plumber found unhandled error:
 Error in plugin 'gulp-less'
Message:
    First argument needs to be a number, array or string. in file undefined line no. undefined
Details:
    lineNumber: undefined
    fileName: undefined
```

If I comment off the sourcemaps instructions, or give the `test.less` file any kind of content, like `body { background: white; }`, no errors occur.

**Comment by heikki** [comment]
Actually it's gulp-less that errors. It could be that sourcemaps does something on empty files that makes it freak out.

**Comment by Pomax** [comment]
I should have been explicit about that: sourcemaps seems to generate output that causes gulp-less to throw an error, suggesting it's not generating the right output on empty files. That's more likely a problem in the package generating the output than the package accepting that generated output.

**Comment by floridoo** [comment]
Probably related to:
* plus3network/gulp-less#121
* plus3network/gulp-less#122

**Comment by heikki** [comment]
This should work now. https://github.com/plus3network/gulp-less/issues/122

@Pomax Can you confirm?

**Comment by floridoo** [comment]
@Pomax I'll close this. If this is unresolved, please reopen.

**Comment by Pomax** [comment]
sorry, I didn't have time to go back to this. I'll reopen if it still happens in the future!
