### ISSUE TITLE
file option is optional

### ISSUE THREAD

**Issue by contra** [floridoo/gulp-sourcemaps#83]
Apparently according to the sourcemaps v3 spec the file attribute should be optional. I am opening this issue on behalf of somebody else.

Original issue: https://github.com/jenius/autoprefixer-stylus/issues/17

Throwing `Source map to be applied is missing the "file" property` when the attribute is not found

**Comment by floridoo** [comment]
@contra `gulp-sourcemaps` is not throwing that error. It handles source maps without it just fine. The exception is thrown by `vinyl-sourcemaps-apply`, which needs a valid `file` property in order to merge the source map with the upstream source maps.

**Comment by trisys3** [comment]
So should we take this to `vinyl-sourcemaps-apply`? Do you have an iinkling as to whether it truly is `vinyl-sourcemaps-apply` or if it's one of *its* dependencies?

**Comment by heikki** [comment]
https://github.com/floridoo/vinyl-sourcemaps-apply/blob/v0.1.4/index.js#L11

**Comment by trisys3** [comment]
So we just take out that line and everything's hunky-dory?

**Comment by heikki** [comment]
I think it's not that simple: https://github.com/floridoo/vinyl-sourcemaps-apply/issues/1#issuecomment-56123235

**Comment by floridoo** [comment]
@trisys3 The `file` property is really needed to properly merge the source maps. If plugins pass a source map without this property errors occur, possibly later in the chain. That's why this is enforced.
It's very easy for plugins to add this property, so I don't really see the issue here.

**Comment by trisys3** [comment]
The issue is sourcemaps don't need the `file` property so the maintainer of the repository of the other issue did not feel the need to add it. I believe the plugin is called after sourcemaps should have been applied, so it wouldn't work to check for it.
