### ISSUE TITLE
Wrong line numbers working with Libsass

### ISSUE THREAD

**Issue by lmartins** [floridoo/gulp-sourcemaps#88]
Im still getting way off results working with a combination of Libsass, Autoprefixer and gulp-sourcemaps.

The maps are being generated but the line-numbers are way off, they only get close to the original sources when the source files are simple and small. Once the project starts to grow the more skewed the results get.

Im not really sure where to report this issue, can you comment please?

**Comment by polarathene** [comment]
Do you have any example project you can share so others can replicate this on their systems? What is your package.json like? Are you using libsass via node-sass? From memory libsass was outputting incorrect sourcemaps with `AAAA` mappings that shouldn't be in there. A recent node-sass update was filtering these out. If your node-sass is out of date(pre 2.0) and using an older version of libsass(pre 3.2), then mappings were already incorrect. Take autoprefixer and any others out of the mix so it's just comping .scss to .css files, verify that your mappings are still faulty, if they still are check your packages or upload an example project. If they're not faulty, then at least we know it's not an issue with how your sass was compiled.

**Comment by DanGamble89** [comment]
Hey, i also have this problem whenever i add things or remove them from my pipeline i get a different result.

My task (I use this in an external task file):

```
function styles(gulp, plugins, config) {
    return function() {
        return gulp.src([
            config.src.scss + '*.scss',
            config.src.scss + '**/*.scss'
        ], {base: config.src.scss})
            .pipe(plugins.sourcemaps.init())
            .pipe(plugins.sass({}))
            .pipe(plugins.sourcemaps.write('.'))
            .pipe(gulp.dest(config.build.css));
    };
}
```

I then get the right paths, css and a map file but the mappings are totally off and rarely point to the right files let alone right line numbers.

Is there anything else i can prove to help track down the problem?
