### ISSUE TITLE
Sources paths incorrect for nested files

### ISSUE THREAD

**Issue by jon-hall** [floridoo/gulp-sourcemaps#89]
When building from TypeScript to ES6 and then to ES5 using gulp-6to5 (on Windows), I'm getting incorrect paths in the sourcemaps' 'sources' property for any files located at paths below our root 'src' directory, e.g. 'src/classes/class1.ts' will have the sources in its sourcemap set to ['classes/class1.ts'] (and the file property set to 'classes/class1.js') which results in the browser expecting the original source file to be located at 'src/classes/classes/class1.ts'.

No combination of changing the value of base in gulp.src, nor specifying a sourceRoot property in gulp-sourcemaps.write appears to remedy this issue.

The problem seems to arise as a result of applying path.relative to the source path at https://github.com/floridoo/gulp-sourcemaps/blob/2a0f222295eb0d2d8ce755ca0652eade7f9af90c/index.js#L70 .  Not sure if there is some configuration property(s) I can modify to get the paths in sources coming out correctly or if this is some kind of bug.

My current gulp task configuration is as follows

    gulp.task('6to5', function () {
        return gulp.src(files.js, { base: './src' })
        .pipe($.sourcemaps.init({ loadMaps: true }))
            .pipe($['6to5']({
                modules: 'ignore',
                blacklist: ['useStrict'],
                format: {
                    indent: {
                        style: '    ',
                        adjustMultilineComment: false
                    }
                }
            }))
            .pipe($.sourcemaps.write('.', {
                includeContent: false
            }))
            .pipe(gulp.dest('./src'));  
    });

and the basic project structure is:
```
|-gulpfile.js
|
|-src
    |-app.ts
    |-app.js.map (created by TypeScript, file: 'app.js', sources: ['app.ts'], 'sourceRoot: '')
    |-app.js (sourcemap generates fine for this file)
    |
    |-classes
        |-class1.ts
        |-class1.js.map (created by TypeScript, file: 'class1.js', sources: ['class1.ts'], sourceRoot: '')
        |-class1.js (sourcemap point to incorrect source path)
```
Any suggestions on remedying this issue would be hugely helpful.

**Comment by polarathene** [comment]
Try applying a relative path to your `base` directory(That'd be `src`), relative from your sourcemaps target destination. Eg `sourcemaps.write('.',{includeContent:false, sourceRoot: '../'})` should work. This should state that from where your sourcemap is, go up one folder, then apply the rest of the path stated in `sources` which sounds like it'll point correctly then. I don't think this is a bug, as mentioned here: https://github.com/floridoo/gulp-sourcemaps you can see that when you set `includeContent:false` that you need to provide the relative path for `sourceRoot` to use, which you haven't, you've only provided the `base` path which is used for defining your path prefixes to files in the `sources` property.

If you're still having no luck, could you supply an example source file, the compiled file and it's sourcemap? Or better an example project like this one: https://github.com/JonRimmer/sourcemaps-bug
