### ISSUE TITLE
Derivate names causing conflicts

### ISSUE THREAD

**Issue by igorlino** [floridoo/gulp-sourcemaps#91]
source: https://github.com/jamesknelson/gulp-rev-replace/issues/25

The problem in short words, is that for effective unique naming of resources and supporting the sourcemap references does not work since the generated map filename contains the original filename. (which under many circumstances would be hard to identify a unique reference)

A good solution would be to be able to slightly change the derivate name of the map file as to make it unique, but still meaningful  and keeping the sourceMappingURL consistent.

Something like:

gulp.task('javascript', function() {
  gulp.src('src/**/*.js')
    .pipe(sourcemaps.init({sourceFilenameExtensionSeparator: '-'}))
      .pipe(plugin1())
      .pipe(plugin2())
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('dist'));
});

so, for a given file 'app.js'  the generated tag is currently:

 sourceMappingURL= app.js.map

after such new parameter it would then become:

 sourceMappingURL= app-js.map

effectively making the both resources unique for whatever referencing or filename manipulation.

**Comment by floridoo** [comment]
I think it is better to fix this in `gulp-rev-replace`. This change would be very specific to your use case and just cause confusion for most of the users.

**Comment by igorlino** [comment]
Sorry for the late response.

Yes true, its a bit specific. Perhaps the option for changing the separator is really not that pretty nor sexy. Would it make a difference if for example we could have a function that could modify/override the path/name as one wishes ?

The [Source Map Revision 3 Proposal ](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/)

tells that the naming convention is optional.

I mean, the library anyways is deriving the name and adding a .map to it.  What about making it more extensible?
I mean,  one of the benefits of gulp itself is the ability to code and enable coding over fixed configurations. This feature goes with that design principle. (I help is needed, I could create a PR if you like).
Important is that the actual map file that is created exists.

So an example:

gulp.task('javascript', function() {
gulp.src('src/*/.js')
.pipe(sourcemaps.init({fullpathMapper: function(fullpath) {
   //whatever logic here. fullpath includes the filename
  return fullpath;
}}))
.pipe(plugin1())
.pipe(plugin2())
.pipe(sourcemaps.write())
.pipe(gulp.dest('dist'));
});
