### ISSUE TITLE
Needs maintainers?

### ISSUE THREAD

**Issue by shinnn** [floridoo/gulp-sourcemaps#94]
Currently this repo has some unreviewed (and important) PRs and open issues, but hasn't been updated recently.

@floridoo I'd happily maintain this repo if you want to collaborate me.

**Comment by floridoo** [comment]
Dependencies are updated in v1.4.0.
@shinn Please send smaller pull requests with more modular changes, that makes it easier to merge them fast

**Comment by shinnn** [comment]
Thanks for your advice. I created more smaller PRs.

**Comment by shinnn** [comment]
@floridoo Could you reconsider reopening this issue? I don't think #94 is not fixed.

**Comment by nmccready** [comment]
@shinnn did you ever get perms? Also we should set up a slack or gitter room, to get everyone in sync. 2.X should not be published until the milestone issues are either cleared up or pushed to 2.0.1  @zacronos
